// SPDX-License-Identifier: (LGPL-2.1 OR BSD-2-Clause)
//
// THIS FILE IS AUTOGENERATED BY CARGO-LIBBPF-GEN!

pub use self::imp::*;

#[allow(renamed_and_removed_lints)]
#[allow(dead_code)]
#[allow(non_snake_case)]
#[allow(non_camel_case_types)]
#[allow(clippy::absolute_paths)]
#[allow(clippy::upper_case_acronyms)]
#[allow(clippy::zero_repeat_side_effects)]
#[warn(single_use_lifetimes)]
mod imp {
    #[allow(unused_imports, clippy::wildcard_imports)]
    use super::*;
    use libbpf_rs::libbpf_sys;
    use libbpf_rs::skel::OpenSkel;
    use libbpf_rs::skel::Skel;
    use libbpf_rs::skel::SkelBuilder;
    use libbpf_rs::AsRawLibbpf as _;
    use libbpf_rs::MapCore as _;
    fn build_skel_config(
    ) -> libbpf_rs::Result<libbpf_rs::__internal_skel::ObjectSkeletonConfig<'static>> {
        let mut builder = libbpf_rs::__internal_skel::ObjectSkeletonConfigBuilder::new(DATA);
        builder
            .name("go_bpf")
            .map("go_bpf.rodata", false)
            .map(".rodata.str1.1", false)
            .prog("handle_hello_int")
            .prog("handle_hello_int_string")
            .prog("handle_hello_struct_pointer")
            .prog("handle_hello_struct_value");
        builder.build()
    }
    pub struct OpenGoMaps<'obj> {
        pub rodata: libbpf_rs::OpenMapMut<'obj>,
        pub rodata_str1_1: libbpf_rs::OpenMapMut<'obj>,
        _phantom: std::marker::PhantomData<&'obj ()>,
    }

    impl<'obj> OpenGoMaps<'obj> {
        #[allow(unused_variables)]
        unsafe fn new(
            config: &libbpf_rs::__internal_skel::ObjectSkeletonConfig<'_>,
            object: &mut libbpf_rs::OpenObject,
        ) -> libbpf_rs::Result<Self> {
            let mut rodata = None;
            let mut rodata_str1_1 = None;
            let object = unsafe {
                std::mem::transmute::<&mut libbpf_rs::OpenObject, &'obj mut libbpf_rs::OpenObject>(
                    object,
                )
            };
            #[allow(clippy::never_loop)]
            for map in object.maps_mut() {
                let name = map.name().to_str().ok_or_else(|| {
                    libbpf_rs::Error::from(std::io::Error::new(
                        std::io::ErrorKind::InvalidData,
                        "map has invalid name",
                    ))
                })?;
                #[allow(clippy::match_single_binding)]
                match name {
                    "go_bpf.rodata" => rodata = Some(map),
                    ".rodata.str1.1" => rodata_str1_1 = Some(map),
                    _ => panic!("encountered unexpected map: `{name}`"),
                }
            }

            let slf = Self {
                rodata: rodata.expect("map `rodata` not present"),
                rodata_str1_1: rodata_str1_1.expect("map `rodata_str1_1` not present"),
                _phantom: std::marker::PhantomData,
            };
            Ok(slf)
        }
    }
    pub struct GoMaps<'obj> {
        pub rodata: libbpf_rs::MapMut<'obj>,
        pub rodata_str1_1: libbpf_rs::MapMut<'obj>,
        _phantom: std::marker::PhantomData<&'obj ()>,
    }

    impl<'obj> GoMaps<'obj> {
        #[allow(unused_variables)]
        unsafe fn new(
            config: &libbpf_rs::__internal_skel::ObjectSkeletonConfig<'_>,
            object: &mut libbpf_rs::Object,
        ) -> libbpf_rs::Result<Self> {
            let mut rodata = None;
            let mut rodata_str1_1 = None;
            let object = unsafe {
                std::mem::transmute::<&mut libbpf_rs::Object, &'obj mut libbpf_rs::Object>(object)
            };
            #[allow(clippy::never_loop)]
            for map in object.maps_mut() {
                let name = map.name().to_str().ok_or_else(|| {
                    libbpf_rs::Error::from(std::io::Error::new(
                        std::io::ErrorKind::InvalidData,
                        "map has invalid name",
                    ))
                })?;
                #[allow(clippy::match_single_binding)]
                match name {
                    "go_bpf.rodata" => rodata = Some(map),
                    ".rodata.str1.1" => rodata_str1_1 = Some(map),
                    _ => panic!("encountered unexpected map: `{name}`"),
                }
            }

            let slf = Self {
                rodata: rodata.expect("map `rodata` not present"),
                rodata_str1_1: rodata_str1_1.expect("map `rodata_str1_1` not present"),
                _phantom: std::marker::PhantomData,
            };
            Ok(slf)
        }
    }
    pub struct OpenGoProgs<'obj> {
        pub handle_hello_int: libbpf_rs::OpenProgramMut<'obj>,
        pub handle_hello_int_string: libbpf_rs::OpenProgramMut<'obj>,
        pub handle_hello_struct_pointer: libbpf_rs::OpenProgramMut<'obj>,
        pub handle_hello_struct_value: libbpf_rs::OpenProgramMut<'obj>,
        _phantom: std::marker::PhantomData<&'obj ()>,
    }

    impl<'obj> OpenGoProgs<'obj> {
        unsafe fn new(object: &mut libbpf_rs::OpenObject) -> libbpf_rs::Result<Self> {
            let mut handle_hello_int = None;
            let mut handle_hello_int_string = None;
            let mut handle_hello_struct_pointer = None;
            let mut handle_hello_struct_value = None;
            let object = unsafe {
                std::mem::transmute::<&mut libbpf_rs::OpenObject, &'obj mut libbpf_rs::OpenObject>(
                    object,
                )
            };
            for prog in object.progs_mut() {
                let name = prog.name().to_str().ok_or_else(|| {
                    libbpf_rs::Error::from(std::io::Error::new(
                        std::io::ErrorKind::InvalidData,
                        "prog has invalid name",
                    ))
                })?;
                match name {
                    "handle_hello_int" => handle_hello_int = Some(prog),
                    "handle_hello_int_string" => handle_hello_int_string = Some(prog),
                    "handle_hello_struct_pointer" => handle_hello_struct_pointer = Some(prog),
                    "handle_hello_struct_value" => handle_hello_struct_value = Some(prog),
                    _ => panic!("encountered unexpected prog: `{name}`"),
                }
            }

            let slf = Self {
                handle_hello_int: handle_hello_int.expect("prog `handle_hello_int` not present"),
                handle_hello_int_string: handle_hello_int_string
                    .expect("prog `handle_hello_int_string` not present"),
                handle_hello_struct_pointer: handle_hello_struct_pointer
                    .expect("prog `handle_hello_struct_pointer` not present"),
                handle_hello_struct_value: handle_hello_struct_value
                    .expect("prog `handle_hello_struct_value` not present"),
                _phantom: std::marker::PhantomData,
            };
            Ok(slf)
        }
    }
    pub struct GoProgs<'obj> {
        pub handle_hello_int: libbpf_rs::ProgramMut<'obj>,
        pub handle_hello_int_string: libbpf_rs::ProgramMut<'obj>,
        pub handle_hello_struct_pointer: libbpf_rs::ProgramMut<'obj>,
        pub handle_hello_struct_value: libbpf_rs::ProgramMut<'obj>,
        _phantom: std::marker::PhantomData<&'obj ()>,
    }

    impl<'obj> GoProgs<'obj> {
        #[allow(unused_variables)]
        fn new(open_progs: OpenGoProgs<'obj>) -> Self {
            Self {
                handle_hello_int: unsafe {
                    libbpf_rs::ProgramMut::new_mut(
                        open_progs.handle_hello_int.as_libbpf_object().as_mut(),
                    )
                },
                handle_hello_int_string: unsafe {
                    libbpf_rs::ProgramMut::new_mut(
                        open_progs
                            .handle_hello_int_string
                            .as_libbpf_object()
                            .as_mut(),
                    )
                },
                handle_hello_struct_pointer: unsafe {
                    libbpf_rs::ProgramMut::new_mut(
                        open_progs
                            .handle_hello_struct_pointer
                            .as_libbpf_object()
                            .as_mut(),
                    )
                },
                handle_hello_struct_value: unsafe {
                    libbpf_rs::ProgramMut::new_mut(
                        open_progs
                            .handle_hello_struct_value
                            .as_libbpf_object()
                            .as_mut(),
                    )
                },
                _phantom: std::marker::PhantomData,
            }
        }
    }
    struct OwnedRef<'obj, O> {
        object: Option<&'obj mut std::mem::MaybeUninit<O>>,
    }

    impl<'obj, O> OwnedRef<'obj, O> {
        /// # Safety
        /// The object has to be initialized.
        unsafe fn new(object: &'obj mut std::mem::MaybeUninit<O>) -> Self {
            Self {
                object: Some(object),
            }
        }

        fn as_ref(&self) -> &O {
            // SAFETY: As per the contract during construction, the
            //         object has to be initialized.
            unsafe { self.object.as_ref().unwrap().assume_init_ref() }
        }

        fn as_mut(&mut self) -> &mut O {
            // SAFETY: As per the contract during construction, the
            //         object has to be initialized.
            unsafe { self.object.as_mut().unwrap().assume_init_mut() }
        }

        fn take(mut self) -> &'obj mut std::mem::MaybeUninit<O> {
            self.object.take().unwrap()
        }
    }

    impl<O> Drop for OwnedRef<'_, O> {
        fn drop(&mut self) {
            if let Some(object) = &mut self.object {
                unsafe { object.assume_init_drop() }
            }
        }
    }

    #[derive(Default)]
    pub struct GoSkelBuilder {
        pub obj_builder: libbpf_rs::ObjectBuilder,
    }

    impl<'obj> GoSkelBuilder {
        fn open_opts_impl(
            self,
            open_opts: *const libbpf_sys::bpf_object_open_opts,
            object: &'obj mut std::mem::MaybeUninit<libbpf_rs::OpenObject>,
        ) -> libbpf_rs::Result<OpenGoSkel<'obj>> {
            let skel_config = build_skel_config()?;
            let skel_ptr = skel_config.as_libbpf_object();

            let ret =
                unsafe { libbpf_sys::bpf_object__open_skeleton(skel_ptr.as_ptr(), open_opts) };
            if ret != 0 {
                return Err(libbpf_rs::Error::from_raw_os_error(-ret));
            }

            // SAFETY: `skel_ptr` points to a valid object after the
            //         open call.
            let obj_ptr = unsafe { *skel_ptr.as_ref().obj };
            // SANITY: `bpf_object__open_skeleton` should have
            //         allocated the object.
            let obj_ptr = std::ptr::NonNull::new(obj_ptr).unwrap();
            // SAFETY: `obj_ptr` points to an opened object after
            //         skeleton open.
            let obj = unsafe { libbpf_rs::OpenObject::from_ptr(obj_ptr) };
            let _obj = object.write(obj);
            // SAFETY: We just wrote initialized data to `object`.
            let mut obj_ref = unsafe { OwnedRef::new(object) };

            #[allow(unused_mut)]
            let mut skel = OpenGoSkel {
                maps: unsafe { OpenGoMaps::new(&skel_config, obj_ref.as_mut())? },
                progs: unsafe { OpenGoProgs::new(obj_ref.as_mut())? },
                obj: obj_ref,
                // SAFETY: Our `struct_ops` type contains only pointers,
                //         which are allowed to be NULL.
                // TODO: Generate and use a `Default` representation
                //       instead, to cut down on unsafe code.
                struct_ops: unsafe { std::mem::zeroed() },
                skel_config,
            };

            Ok(skel)
        }
    }

    impl<'obj> SkelBuilder<'obj> for GoSkelBuilder {
        type Output = OpenGoSkel<'obj>;
        fn open(
            self,
            object: &'obj mut std::mem::MaybeUninit<libbpf_rs::OpenObject>,
        ) -> libbpf_rs::Result<OpenGoSkel<'obj>> {
            self.open_opts_impl(std::ptr::null(), object)
        }

        fn open_opts(
            self,
            open_opts: libbpf_sys::bpf_object_open_opts,
            object: &'obj mut std::mem::MaybeUninit<libbpf_rs::OpenObject>,
        ) -> libbpf_rs::Result<OpenGoSkel<'obj>> {
            self.open_opts_impl(&open_opts, object)
        }

        fn object_builder(&self) -> &libbpf_rs::ObjectBuilder {
            &self.obj_builder
        }
        fn object_builder_mut(&mut self) -> &mut libbpf_rs::ObjectBuilder {
            &mut self.obj_builder
        }
    }

    #[derive(Debug, Clone)]
    #[repr(C)]
    pub struct StructOps {}

    impl StructOps {}
    pub mod types {
        #[allow(unused_imports)]
        use super::*;
        #[derive(Debug, Default, Copy, Clone)]
        #[repr(C)]
        pub struct pt_regs {
            pub r15: u64,
            pub r14: u64,
            pub r13: u64,
            pub r12: u64,
            pub bp: u64,
            pub bx: u64,
            pub r11: u64,
            pub r10: u64,
            pub r9: u64,
            pub r8: u64,
            pub ax: u64,
            pub cx: u64,
            pub dx: u64,
            pub si: u64,
            pub di: u64,
            pub orig_ax: u64,
            pub ip: u64,
            pub cs: u64,
            pub flags: u64,
            pub sp: u64,
            pub ss: u64,
        }
        #[derive(Debug, Copy, Clone)]
        #[repr(C)]
        pub struct license {
            pub LICENSE: [i8; 13],
        }
        #[derive(Debug, Copy, Clone)]
        #[repr(C)]
        pub struct rodata {}
    }
    pub struct OpenGoSkel<'obj> {
        obj: OwnedRef<'obj, libbpf_rs::OpenObject>,
        pub maps: OpenGoMaps<'obj>,
        pub progs: OpenGoProgs<'obj>,
        pub struct_ops: StructOps,
        skel_config: libbpf_rs::__internal_skel::ObjectSkeletonConfig<'obj>,
    }

    impl<'obj> OpenSkel<'obj> for OpenGoSkel<'obj> {
        type Output = GoSkel<'obj>;
        fn load(self) -> libbpf_rs::Result<GoSkel<'obj>> {
            let skel_ptr = self.skel_config.as_libbpf_object().as_ptr();

            let ret = unsafe { libbpf_sys::bpf_object__load_skeleton(skel_ptr) };
            if ret != 0 {
                return Err(libbpf_rs::Error::from_raw_os_error(-ret));
            }

            let obj_ref = self.obj.take();
            let open_obj = std::mem::replace(obj_ref, std::mem::MaybeUninit::uninit());
            // SAFETY: `open_obj` is guaranteed to be properly
            //         initialized as it came from an `OwnedRef`.
            let obj_ptr = unsafe { open_obj.assume_init().take_ptr() };
            // SAFETY: `obj_ptr` points to a loaded object after
            //         skeleton load.
            let obj = unsafe { libbpf_rs::Object::from_ptr(obj_ptr) };
            // SAFETY: `OpenObject` and `Object` are guaranteed to
            //         have the same memory layout.
            let obj_ref = unsafe {
                std::mem::transmute::<
                    &'obj mut std::mem::MaybeUninit<libbpf_rs::OpenObject>,
                    &'obj mut std::mem::MaybeUninit<libbpf_rs::Object>,
                >(obj_ref)
            };
            let _obj = obj_ref.write(obj);
            // SAFETY: We just wrote initialized data to `obj_ref`.
            let mut obj_ref = unsafe { OwnedRef::new(obj_ref) };

            Ok(GoSkel {
                maps: unsafe { GoMaps::new(&self.skel_config, obj_ref.as_mut())? },
                progs: GoProgs::new(self.progs),
                obj: obj_ref,
                struct_ops: self.struct_ops,
                skel_config: self.skel_config,
                links: GoLinks::default(),
            })
        }

        fn open_object(&self) -> &libbpf_rs::OpenObject {
            self.obj.as_ref()
        }

        fn open_object_mut(&mut self) -> &mut libbpf_rs::OpenObject {
            self.obj.as_mut()
        }
    }
    #[derive(Default)]
    pub struct GoLinks {
        pub handle_hello_int: Option<libbpf_rs::Link>,
        pub handle_hello_int_string: Option<libbpf_rs::Link>,
        pub handle_hello_struct_pointer: Option<libbpf_rs::Link>,
        pub handle_hello_struct_value: Option<libbpf_rs::Link>,
    }
    pub struct GoSkel<'obj> {
        obj: OwnedRef<'obj, libbpf_rs::Object>,
        pub maps: GoMaps<'obj>,
        pub progs: GoProgs<'obj>,
        struct_ops: StructOps,
        skel_config: libbpf_rs::__internal_skel::ObjectSkeletonConfig<'obj>,
        pub links: GoLinks,
    }

    unsafe impl Send for GoSkel<'_> {}
    unsafe impl Sync for GoSkel<'_> {}

    impl<'obj> Skel<'obj> for GoSkel<'obj> {
        fn object(&self) -> &libbpf_rs::Object {
            self.obj.as_ref()
        }

        fn object_mut(&mut self) -> &mut libbpf_rs::Object {
            self.obj.as_mut()
        }
        fn attach(&mut self) -> libbpf_rs::Result<()> {
            let skel_ptr = self.skel_config.as_libbpf_object().as_ptr();
            let ret = unsafe { libbpf_sys::bpf_object__attach_skeleton(skel_ptr) };
            if ret != 0 {
                return Err(libbpf_rs::Error::from_raw_os_error(-ret));
            }

            self.links = GoLinks {
                handle_hello_int: core::ptr::NonNull::new(self.skel_config.prog_link_ptr(0)?)
                    .map(|ptr| unsafe { libbpf_rs::Link::from_ptr(ptr) }),
                handle_hello_int_string: core::ptr::NonNull::new(
                    self.skel_config.prog_link_ptr(1)?,
                )
                .map(|ptr| unsafe { libbpf_rs::Link::from_ptr(ptr) }),
                handle_hello_struct_pointer: core::ptr::NonNull::new(
                    self.skel_config.prog_link_ptr(2)?,
                )
                .map(|ptr| unsafe { libbpf_rs::Link::from_ptr(ptr) }),
                handle_hello_struct_value: core::ptr::NonNull::new(
                    self.skel_config.prog_link_ptr(3)?,
                )
                .map(|ptr| unsafe { libbpf_rs::Link::from_ptr(ptr) }),
            };

            Ok(())
        }
    }
    impl GoSkel<'_> {
        pub fn struct_ops_raw(&self) -> *const StructOps {
            &self.struct_ops
        }

        pub fn struct_ops(&self) -> &StructOps {
            &self.struct_ops
        }
    }
    const DATA: &[u8] = &[
        127, 69, 76, 70, 2, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 247, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 112, 53, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 64, 0, 0, 0, 0,
        0, 64, 0, 16, 0, 1, 0, 0, 46, 115, 116, 114, 116, 97, 98, 0, 46, 115, 121, 109, 116, 97,
        98, 0, 117, 112, 114, 111, 98, 101, 47, 109, 97, 105, 110, 46, 104, 101, 108, 108, 111, 95,
        105, 110, 116, 0, 117, 112, 114, 111, 98, 101, 47, 109, 97, 105, 110, 46, 104, 101, 108,
        108, 111, 95, 105, 110, 116, 95, 115, 116, 114, 105, 110, 103, 0, 117, 112, 114, 111, 98,
        101, 47, 104, 97, 110, 100, 108, 101, 95, 104, 101, 108, 108, 111, 95, 115, 116, 114, 117,
        99, 116, 95, 112, 111, 105, 110, 116, 101, 114, 0, 117, 112, 114, 111, 98, 101, 47, 104,
        97, 110, 100, 108, 101, 95, 104, 101, 108, 108, 111, 95, 115, 116, 114, 117, 99, 116, 95,
        118, 97, 108, 117, 101, 0, 108, 105, 99, 101, 110, 115, 101, 0, 46, 114, 111, 100, 97, 116,
        97, 0, 46, 114, 111, 100, 97, 116, 97, 46, 115, 116, 114, 49, 46, 49, 0, 103, 111, 46, 98,
        112, 102, 46, 99, 0, 46, 76, 46, 115, 116, 114, 0, 46, 76, 46, 115, 116, 114, 46, 49, 51,
        0, 76, 66, 66, 49, 95, 49, 48, 0, 76, 66, 66, 49, 95, 49, 49, 0, 76, 66, 66, 49, 95, 52, 0,
        76, 66, 66, 49, 95, 54, 0, 76, 66, 66, 49, 95, 56, 0, 76, 66, 66, 49, 95, 57, 0, 76, 66,
        66, 50, 95, 49, 48, 0, 76, 66, 66, 50, 95, 49, 50, 0, 76, 66, 66, 50, 95, 49, 53, 0, 76,
        66, 66, 50, 95, 49, 55, 0, 76, 66, 66, 50, 95, 49, 56, 0, 76, 66, 66, 50, 95, 49, 57, 0,
        76, 66, 66, 50, 95, 50, 0, 76, 66, 66, 50, 95, 52, 0, 76, 66, 66, 50, 95, 54, 0, 76, 66,
        66, 50, 95, 55, 0, 76, 66, 66, 51, 95, 49, 49, 0, 76, 66, 66, 51, 95, 49, 51, 0, 76, 66,
        66, 51, 95, 49, 52, 0, 76, 66, 66, 51, 95, 49, 53, 0, 76, 66, 66, 51, 95, 50, 0, 76, 66,
        66, 51, 95, 51, 0, 76, 66, 66, 51, 95, 53, 0, 76, 66, 66, 51, 95, 54, 0, 76, 66, 66, 51,
        95, 56, 0, 76, 66, 66, 51, 95, 57, 0, 104, 97, 110, 100, 108, 101, 95, 104, 101, 108, 108,
        111, 95, 105, 110, 116, 46, 95, 95, 95, 95, 102, 109, 116, 0, 104, 97, 110, 100, 108, 101,
        95, 104, 101, 108, 108, 111, 95, 105, 110, 116, 46, 95, 95, 95, 95, 102, 109, 116, 46, 49,
        0, 104, 97, 110, 100, 108, 101, 95, 104, 101, 108, 108, 111, 95, 105, 110, 116, 95, 115,
        116, 114, 105, 110, 103, 46, 95, 95, 95, 95, 102, 109, 116, 0, 104, 97, 110, 100, 108, 101,
        95, 104, 101, 108, 108, 111, 95, 105, 110, 116, 95, 115, 116, 114, 105, 110, 103, 46, 95,
        95, 95, 95, 102, 109, 116, 46, 50, 0, 104, 97, 110, 100, 108, 101, 95, 104, 101, 108, 108,
        111, 95, 105, 110, 116, 95, 115, 116, 114, 105, 110, 103, 46, 95, 95, 95, 95, 102, 109,
        116, 46, 51, 0, 104, 97, 110, 100, 108, 101, 95, 104, 101, 108, 108, 111, 95, 105, 110,
        116, 95, 115, 116, 114, 105, 110, 103, 46, 95, 95, 95, 95, 102, 109, 116, 46, 52, 0, 104,
        97, 110, 100, 108, 101, 95, 104, 101, 108, 108, 111, 95, 115, 116, 114, 117, 99, 116, 95,
        112, 111, 105, 110, 116, 101, 114, 46, 95, 95, 95, 95, 102, 109, 116, 0, 104, 97, 110, 100,
        108, 101, 95, 104, 101, 108, 108, 111, 95, 115, 116, 114, 117, 99, 116, 95, 112, 111, 105,
        110, 116, 101, 114, 46, 95, 95, 95, 95, 102, 109, 116, 46, 49, 48, 0, 104, 97, 110, 100,
        108, 101, 95, 104, 101, 108, 108, 111, 95, 115, 116, 114, 117, 99, 116, 95, 112, 111, 105,
        110, 116, 101, 114, 46, 95, 95, 95, 95, 102, 109, 116, 46, 49, 49, 0, 104, 97, 110, 100,
        108, 101, 95, 104, 101, 108, 108, 111, 95, 115, 116, 114, 117, 99, 116, 95, 112, 111, 105,
        110, 116, 101, 114, 46, 95, 95, 95, 95, 102, 109, 116, 46, 49, 50, 0, 104, 97, 110, 100,
        108, 101, 95, 104, 101, 108, 108, 111, 95, 115, 116, 114, 117, 99, 116, 95, 112, 111, 105,
        110, 116, 101, 114, 46, 95, 95, 95, 95, 102, 109, 116, 46, 53, 0, 104, 97, 110, 100, 108,
        101, 95, 104, 101, 108, 108, 111, 95, 115, 116, 114, 117, 99, 116, 95, 112, 111, 105, 110,
        116, 101, 114, 46, 95, 95, 95, 95, 102, 109, 116, 46, 54, 0, 104, 97, 110, 100, 108, 101,
        95, 104, 101, 108, 108, 111, 95, 115, 116, 114, 117, 99, 116, 95, 112, 111, 105, 110, 116,
        101, 114, 46, 95, 95, 95, 95, 102, 109, 116, 46, 55, 0, 104, 97, 110, 100, 108, 101, 95,
        104, 101, 108, 108, 111, 95, 115, 116, 114, 117, 99, 116, 95, 112, 111, 105, 110, 116, 101,
        114, 46, 95, 95, 95, 95, 102, 109, 116, 46, 56, 0, 104, 97, 110, 100, 108, 101, 95, 104,
        101, 108, 108, 111, 95, 115, 116, 114, 117, 99, 116, 95, 112, 111, 105, 110, 116, 101, 114,
        46, 95, 95, 95, 95, 102, 109, 116, 46, 57, 0, 104, 97, 110, 100, 108, 101, 95, 104, 101,
        108, 108, 111, 95, 115, 116, 114, 117, 99, 116, 95, 118, 97, 108, 117, 101, 46, 95, 95, 95,
        95, 102, 109, 116, 0, 104, 97, 110, 100, 108, 101, 95, 104, 101, 108, 108, 111, 95, 115,
        116, 114, 117, 99, 116, 95, 118, 97, 108, 117, 101, 46, 95, 95, 95, 95, 102, 109, 116, 46,
        49, 52, 0, 104, 97, 110, 100, 108, 101, 95, 104, 101, 108, 108, 111, 95, 115, 116, 114,
        117, 99, 116, 95, 118, 97, 108, 117, 101, 46, 95, 95, 95, 95, 102, 109, 116, 46, 49, 53, 0,
        104, 97, 110, 100, 108, 101, 95, 104, 101, 108, 108, 111, 95, 115, 116, 114, 117, 99, 116,
        95, 118, 97, 108, 117, 101, 46, 95, 95, 95, 95, 102, 109, 116, 46, 49, 54, 0, 104, 97, 110,
        100, 108, 101, 95, 104, 101, 108, 108, 111, 95, 115, 116, 114, 117, 99, 116, 95, 118, 97,
        108, 117, 101, 46, 95, 95, 95, 95, 102, 109, 116, 46, 49, 55, 0, 104, 97, 110, 100, 108,
        101, 95, 104, 101, 108, 108, 111, 95, 115, 116, 114, 117, 99, 116, 95, 118, 97, 108, 117,
        101, 46, 95, 95, 95, 95, 102, 109, 116, 46, 49, 56, 0, 104, 97, 110, 100, 108, 101, 95,
        104, 101, 108, 108, 111, 95, 115, 116, 114, 117, 99, 116, 95, 118, 97, 108, 117, 101, 46,
        95, 95, 95, 95, 102, 109, 116, 46, 49, 57, 0, 104, 97, 110, 100, 108, 101, 95, 104, 101,
        108, 108, 111, 95, 115, 116, 114, 117, 99, 116, 95, 118, 97, 108, 117, 101, 46, 95, 95, 95,
        95, 102, 109, 116, 46, 50, 48, 0, 76, 73, 67, 69, 78, 83, 69, 0, 104, 97, 110, 100, 108,
        101, 95, 104, 101, 108, 108, 111, 95, 105, 110, 116, 0, 104, 97, 110, 100, 108, 101, 95,
        104, 101, 108, 108, 111, 95, 105, 110, 116, 95, 115, 116, 114, 105, 110, 103, 0, 104, 97,
        110, 100, 108, 101, 95, 104, 101, 108, 108, 111, 95, 115, 116, 114, 117, 99, 116, 95, 112,
        111, 105, 110, 116, 101, 114, 0, 104, 97, 110, 100, 108, 101, 95, 104, 101, 108, 108, 111,
        95, 115, 116, 114, 117, 99, 116, 95, 118, 97, 108, 117, 101, 0, 46, 114, 101, 108, 117,
        112, 114, 111, 98, 101, 47, 109, 97, 105, 110, 46, 104, 101, 108, 108, 111, 95, 105, 110,
        116, 0, 46, 114, 101, 108, 117, 112, 114, 111, 98, 101, 47, 109, 97, 105, 110, 46, 104,
        101, 108, 108, 111, 95, 105, 110, 116, 95, 115, 116, 114, 105, 110, 103, 0, 46, 114, 101,
        108, 117, 112, 114, 111, 98, 101, 47, 104, 97, 110, 100, 108, 101, 95, 104, 101, 108, 108,
        111, 95, 115, 116, 114, 117, 99, 116, 95, 112, 111, 105, 110, 116, 101, 114, 0, 46, 114,
        101, 108, 117, 112, 114, 111, 98, 101, 47, 104, 97, 110, 100, 108, 101, 95, 104, 101, 108,
        108, 111, 95, 115, 116, 114, 117, 99, 116, 95, 118, 97, 108, 117, 101, 0, 46, 66, 84, 70,
        0, 46, 66, 84, 70, 46, 101, 120, 116, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 167, 0, 0, 0, 4, 0, 241, 255, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 176, 0, 0, 0, 1, 0, 9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0,
        183, 0, 0, 0, 1, 0, 9, 0, 5, 0, 0, 0, 0, 0, 0, 0, 6, 0, 0, 0, 0, 0, 0, 0, 193, 0, 0, 0, 0,
        0, 4, 0, 216, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 201, 0, 0, 0, 0, 0, 4, 0, 224,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 209, 0, 0, 0, 0, 0, 4, 0, 240, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 216, 0, 0, 0, 0, 0, 4, 0, 56, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 223, 0, 0, 0, 0, 0, 4, 0, 104, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        230, 0, 0, 0, 0, 0, 4, 0, 192, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 237, 0, 0, 0,
        0, 0, 5, 0, 160, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 245, 0, 0, 0, 0, 0, 5, 0, 40,
        2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 253, 0, 0, 0, 0, 0, 5, 0, 200, 2, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 1, 0, 0, 0, 0, 5, 0, 72, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 13, 1, 0, 0, 0, 0, 5, 0, 96, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 21,
        1, 0, 0, 0, 0, 5, 0, 104, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 29, 1, 0, 0, 0, 0,
        5, 0, 56, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 36, 1, 0, 0, 0, 0, 5, 0, 136, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 43, 1, 0, 0, 0, 0, 5, 0, 16, 2, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 50, 1, 0, 0, 0, 0, 5, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 57, 1, 0, 0, 0, 0, 6, 0, 104, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 65, 1, 0, 0,
        0, 0, 6, 0, 248, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 73, 1, 0, 0, 0, 0, 6, 0, 192,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 81, 1, 0, 0, 0, 0, 6, 0, 48, 1, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 89, 1, 0, 0, 0, 0, 6, 0, 160, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 96, 1, 0, 0, 0, 0, 6, 0, 208, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 103,
        1, 0, 0, 0, 0, 6, 0, 32, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 110, 1, 0, 0, 0, 0,
        6, 0, 64, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 117, 1, 0, 0, 0, 0, 6, 0, 240, 1, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 124, 1, 0, 0, 0, 0, 6, 0, 24, 2, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 131, 1, 0, 0, 1, 0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 27, 0, 0, 0, 0,
        0, 0, 0, 156, 1, 0, 0, 1, 0, 8, 0, 27, 0, 0, 0, 0, 0, 0, 0, 18, 0, 0, 0, 0, 0, 0, 0, 183,
        1, 0, 0, 1, 0, 8, 0, 45, 0, 0, 0, 0, 0, 0, 0, 28, 0, 0, 0, 0, 0, 0, 0, 215, 1, 0, 0, 1, 0,
        8, 0, 73, 0, 0, 0, 0, 0, 0, 0, 23, 0, 0, 0, 0, 0, 0, 0, 249, 1, 0, 0, 1, 0, 8, 0, 96, 0, 0,
        0, 0, 0, 0, 0, 26, 0, 0, 0, 0, 0, 0, 0, 27, 2, 0, 0, 1, 0, 8, 0, 122, 0, 0, 0, 0, 0, 0, 0,
        34, 0, 0, 0, 0, 0, 0, 0, 61, 2, 0, 0, 1, 0, 8, 0, 156, 0, 0, 0, 0, 0, 0, 0, 23, 0, 0, 0, 0,
        0, 0, 0, 97, 2, 0, 0, 1, 0, 8, 0, 53, 1, 0, 0, 0, 0, 0, 0, 10, 0, 0, 0, 0, 0, 0, 0, 136, 2,
        0, 0, 1, 0, 8, 0, 63, 1, 0, 0, 0, 0, 0, 0, 13, 0, 0, 0, 0, 0, 0, 0, 175, 2, 0, 0, 1, 0, 8,
        0, 76, 1, 0, 0, 0, 0, 0, 0, 12, 0, 0, 0, 0, 0, 0, 0, 214, 2, 0, 0, 1, 0, 8, 0, 179, 0, 0,
        0, 0, 0, 0, 0, 31, 0, 0, 0, 0, 0, 0, 0, 252, 2, 0, 0, 1, 0, 8, 0, 210, 0, 0, 0, 0, 0, 0, 0,
        28, 0, 0, 0, 0, 0, 0, 0, 34, 3, 0, 0, 1, 0, 8, 0, 238, 0, 0, 0, 0, 0, 0, 0, 20, 0, 0, 0, 0,
        0, 0, 0, 72, 3, 0, 0, 1, 0, 8, 0, 2, 1, 0, 0, 0, 0, 0, 0, 28, 0, 0, 0, 0, 0, 0, 0, 110, 3,
        0, 0, 1, 0, 8, 0, 30, 1, 0, 0, 0, 0, 0, 0, 23, 0, 0, 0, 0, 0, 0, 0, 148, 3, 0, 0, 1, 0, 8,
        0, 88, 1, 0, 0, 0, 0, 0, 0, 28, 0, 0, 0, 0, 0, 0, 0, 182, 3, 0, 0, 1, 0, 8, 0, 116, 1, 0,
        0, 0, 0, 0, 0, 23, 0, 0, 0, 0, 0, 0, 0, 219, 3, 0, 0, 1, 0, 8, 0, 139, 1, 0, 0, 0, 0, 0, 0,
        19, 0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 1, 0, 8, 0, 158, 1, 0, 0, 0, 0, 0, 0, 28, 0, 0, 0, 0,
        0, 0, 0, 37, 4, 0, 0, 1, 0, 8, 0, 186, 1, 0, 0, 0, 0, 0, 0, 23, 0, 0, 0, 0, 0, 0, 0, 74, 4,
        0, 0, 1, 0, 8, 0, 209, 1, 0, 0, 0, 0, 0, 0, 35, 0, 0, 0, 0, 0, 0, 0, 111, 4, 0, 0, 1, 0, 8,
        0, 244, 1, 0, 0, 0, 0, 0, 0, 10, 0, 0, 0, 0, 0, 0, 0, 148, 4, 0, 0, 1, 0, 8, 0, 254, 1, 0,
        0, 0, 0, 0, 0, 12, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 3, 0, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3,
        0, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 8, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 185, 4, 0, 0, 17, 0, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        13, 0, 0, 0, 0, 0, 0, 0, 193, 4, 0, 0, 18, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 96, 0, 0, 0, 0,
        0, 0, 0, 210, 4, 0, 0, 18, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 168, 1, 0, 0, 0, 0, 0, 0, 234,
        4, 0, 0, 18, 0, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 120, 3, 0, 0, 0, 0, 0, 0, 6, 5, 0, 0, 18, 0,
        6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 24, 3, 0, 0, 0, 0, 0, 0, 121, 22, 80, 0, 0, 0, 0, 0, 24, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 183, 2, 0, 0, 27, 0, 0, 0, 133, 0, 0, 0, 6, 0, 0,
        0, 24, 1, 0, 0, 27, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 183, 2, 0, 0, 18, 0, 0, 0, 191, 99, 0,
        0, 0, 0, 0, 0, 133, 0, 0, 0, 6, 0, 0, 0, 183, 0, 0, 0, 0, 0, 0, 0, 149, 0, 0, 0, 0, 0, 0,
        0, 121, 19, 40, 0, 0, 0, 0, 0, 21, 3, 22, 0, 0, 0, 0, 0, 121, 22, 88, 0, 0, 0, 0, 0, 183,
        2, 0, 0, 1, 0, 0, 0, 109, 98, 19, 0, 0, 0, 0, 0, 121, 23, 80, 0, 0, 0, 0, 0, 183, 1, 0, 0,
        0, 0, 0, 0, 115, 26, 248, 255, 0, 0, 0, 0, 123, 26, 240, 255, 0, 0, 0, 0, 123, 26, 232,
        255, 0, 0, 0, 0, 123, 26, 224, 255, 0, 0, 0, 0, 123, 26, 216, 255, 0, 0, 0, 0, 123, 26,
        208, 255, 0, 0, 0, 0, 123, 26, 200, 255, 0, 0, 0, 0, 123, 26, 192, 255, 0, 0, 0, 0, 123,
        26, 184, 255, 0, 0, 0, 0, 183, 1, 0, 0, 66, 0, 0, 0, 45, 97, 12, 0, 0, 0, 0, 0, 24, 1, 0,
        0, 45, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 183, 2, 0, 0, 28, 0, 0, 0, 191, 99, 0, 0, 0, 0, 0,
        0, 133, 0, 0, 0, 6, 0, 0, 0, 5, 0, 4, 0, 0, 0, 0, 0, 24, 1, 0, 0, 122, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 183, 2, 0, 0, 34, 0, 0, 0, 133, 0, 0, 0, 6, 0, 0, 0, 183, 0, 0, 0, 0, 0, 0, 0,
        149, 0, 0, 0, 0, 0, 0, 0, 191, 161, 0, 0, 0, 0, 0, 0, 7, 1, 0, 0, 184, 255, 255, 255, 191,
        98, 0, 0, 0, 0, 0, 0, 133, 0, 0, 0, 112, 0, 0, 0, 101, 0, 4, 0, 255, 255, 255, 255, 24, 1,
        0, 0, 73, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 183, 2, 0, 0, 23, 0, 0, 0, 5, 0, 244, 255, 0, 0,
        0, 0, 37, 6, 5, 0, 64, 0, 0, 0, 191, 161, 0, 0, 0, 0, 0, 0, 7, 1, 0, 0, 184, 255, 255, 255,
        15, 97, 0, 0, 0, 0, 0, 0, 183, 2, 0, 0, 0, 0, 0, 0, 115, 33, 0, 0, 0, 0, 0, 0, 191, 164, 0,
        0, 0, 0, 0, 0, 7, 4, 0, 0, 184, 255, 255, 255, 24, 1, 0, 0, 96, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 183, 2, 0, 0, 26, 0, 0, 0, 191, 115, 0, 0, 0, 0, 0, 0, 133, 0, 0, 0, 6, 0, 0, 0, 5,
        0, 231, 255, 0, 0, 0, 0, 121, 19, 80, 0, 0, 0, 0, 0, 85, 3, 5, 0, 0, 0, 0, 0, 24, 1, 0, 0,
        156, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 183, 2, 0, 0, 23, 0, 0, 0, 133, 0, 0, 0, 6, 0, 0, 0,
        5, 0, 102, 0, 0, 0, 0, 0, 191, 161, 0, 0, 0, 0, 0, 0, 7, 1, 0, 0, 200, 255, 255, 255, 183,
        2, 0, 0, 56, 0, 0, 0, 133, 0, 0, 0, 112, 0, 0, 0, 21, 0, 5, 0, 0, 0, 0, 0, 24, 1, 0, 0,
        179, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 183, 2, 0, 0, 31, 0, 0, 0, 133, 0, 0, 0, 6, 0, 0, 0,
        5, 0, 92, 0, 0, 0, 0, 0, 183, 1, 0, 0, 0, 0, 0, 0, 123, 26, 192, 255, 0, 0, 0, 0, 123, 26,
        184, 255, 0, 0, 0, 0, 123, 26, 176, 255, 0, 0, 0, 0, 123, 26, 168, 255, 0, 0, 0, 0, 123,
        26, 160, 255, 0, 0, 0, 0, 123, 26, 152, 255, 0, 0, 0, 0, 123, 26, 144, 255, 0, 0, 0, 0,
        123, 26, 136, 255, 0, 0, 0, 0, 121, 166, 208, 255, 0, 0, 0, 0, 183, 1, 0, 0, 65, 0, 0, 0,
        45, 97, 3, 0, 0, 0, 0, 0, 24, 1, 0, 0, 210, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 0, 34, 0,
        0, 0, 0, 0, 191, 97, 0, 0, 0, 0, 0, 0, 87, 1, 0, 0, 191, 255, 255, 255, 21, 1, 17, 0, 0, 0,
        0, 0, 121, 163, 200, 255, 0, 0, 0, 0, 191, 161, 0, 0, 0, 0, 0, 0, 7, 1, 0, 0, 136, 255,
        255, 255, 191, 98, 0, 0, 0, 0, 0, 0, 133, 0, 0, 0, 112, 0, 0, 0, 85, 0, 11, 0, 0, 0, 0, 0,
        191, 163, 0, 0, 0, 0, 0, 0, 7, 3, 0, 0, 136, 255, 255, 255, 191, 49, 0, 0, 0, 0, 0, 0, 15,
        97, 0, 0, 0, 0, 0, 0, 183, 2, 0, 0, 0, 0, 0, 0, 115, 33, 0, 0, 0, 0, 0, 0, 121, 164, 208,
        255, 0, 0, 0, 0, 24, 1, 0, 0, 238, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 183, 2, 0, 0, 20, 0, 0,
        0, 133, 0, 0, 0, 6, 0, 0, 0, 183, 1, 0, 0, 0, 0, 0, 0, 123, 26, 128, 255, 0, 0, 0, 0, 123,
        26, 120, 255, 0, 0, 0, 0, 123, 26, 112, 255, 0, 0, 0, 0, 123, 26, 104, 255, 0, 0, 0, 0,
        123, 26, 96, 255, 0, 0, 0, 0, 123, 26, 88, 255, 0, 0, 0, 0, 123, 26, 80, 255, 0, 0, 0, 0,
        123, 26, 72, 255, 0, 0, 0, 0, 121, 166, 224, 255, 0, 0, 0, 0, 183, 1, 0, 0, 65, 0, 0, 0,
        45, 97, 5, 0, 0, 0, 0, 0, 24, 1, 0, 0, 2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 183, 2, 0, 0,
        28, 0, 0, 0, 191, 99, 0, 0, 0, 0, 0, 0, 5, 0, 39, 0, 0, 0, 0, 0, 191, 97, 0, 0, 0, 0, 0, 0,
        87, 1, 0, 0, 191, 255, 255, 255, 21, 1, 17, 0, 0, 0, 0, 0, 121, 163, 216, 255, 0, 0, 0, 0,
        191, 161, 0, 0, 0, 0, 0, 0, 7, 1, 0, 0, 72, 255, 255, 255, 191, 98, 0, 0, 0, 0, 0, 0, 133,
        0, 0, 0, 112, 0, 0, 0, 85, 0, 11, 0, 0, 0, 0, 0, 191, 163, 0, 0, 0, 0, 0, 0, 7, 3, 0, 0,
        72, 255, 255, 255, 191, 49, 0, 0, 0, 0, 0, 0, 15, 97, 0, 0, 0, 0, 0, 0, 183, 2, 0, 0, 0, 0,
        0, 0, 115, 33, 0, 0, 0, 0, 0, 0, 121, 164, 224, 255, 0, 0, 0, 0, 24, 1, 0, 0, 30, 1, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 183, 2, 0, 0, 23, 0, 0, 0, 133, 0, 0, 0, 6, 0, 0, 0, 121, 163, 232,
        255, 0, 0, 0, 0, 24, 1, 0, 0, 53, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 183, 2, 0, 0, 10, 0, 0,
        0, 133, 0, 0, 0, 6, 0, 0, 0, 121, 163, 240, 255, 0, 0, 0, 0, 24, 1, 0, 0, 63, 1, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 183, 2, 0, 0, 13, 0, 0, 0, 133, 0, 0, 0, 6, 0, 0, 0, 24, 3, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 113, 161, 248, 255, 0, 0, 0, 0, 21, 1, 2, 0, 0, 0, 0, 0,
        24, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 24, 1, 0, 0, 76, 1, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 183, 2, 0, 0, 12, 0, 0, 0, 133, 0, 0, 0, 6, 0, 0, 0, 183, 0, 0, 0, 0, 0, 0, 0,
        149, 0, 0, 0, 0, 0, 0, 0, 121, 19, 72, 0, 0, 0, 0, 0, 121, 22, 104, 0, 0, 0, 0, 0, 121, 23,
        112, 0, 0, 0, 0, 0, 121, 24, 80, 0, 0, 0, 0, 0, 121, 25, 40, 0, 0, 0, 0, 0, 183, 2, 0, 0,
        0, 0, 0, 0, 123, 42, 248, 255, 0, 0, 0, 0, 123, 42, 240, 255, 0, 0, 0, 0, 123, 42, 232,
        255, 0, 0, 0, 0, 123, 42, 224, 255, 0, 0, 0, 0, 123, 42, 216, 255, 0, 0, 0, 0, 123, 42,
        208, 255, 0, 0, 0, 0, 123, 42, 200, 255, 0, 0, 0, 0, 123, 42, 192, 255, 0, 0, 0, 0, 191,
        145, 0, 0, 0, 0, 0, 0, 103, 1, 0, 0, 32, 0, 0, 0, 199, 1, 0, 0, 32, 0, 0, 0, 109, 18, 2, 0,
        0, 0, 0, 0, 183, 2, 0, 0, 64, 0, 0, 0, 45, 18, 6, 0, 0, 0, 0, 0, 24, 1, 0, 0, 88, 1, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 183, 2, 0, 0, 28, 0, 0, 0, 191, 147, 0, 0, 0, 0, 0, 0, 133, 0, 0,
        0, 6, 0, 0, 0, 5, 0, 12, 0, 0, 0, 0, 0, 123, 58, 120, 255, 0, 0, 0, 0, 87, 9, 0, 0, 63, 0,
        0, 0, 191, 161, 0, 0, 0, 0, 0, 0, 7, 1, 0, 0, 192, 255, 255, 255, 191, 146, 0, 0, 0, 0, 0,
        0, 191, 131, 0, 0, 0, 0, 0, 0, 133, 0, 0, 0, 112, 0, 0, 0, 21, 0, 6, 0, 0, 0, 0, 0, 24, 1,
        0, 0, 116, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 183, 2, 0, 0, 23, 0, 0, 0, 133, 0, 0, 0, 6, 0,
        0, 0, 183, 0, 0, 0, 0, 0, 0, 0, 149, 0, 0, 0, 0, 0, 0, 0, 191, 163, 0, 0, 0, 0, 0, 0, 7, 3,
        0, 0, 192, 255, 255, 255, 24, 1, 0, 0, 139, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 183, 2, 0, 0,
        19, 0, 0, 0, 191, 148, 0, 0, 0, 0, 0, 0, 133, 0, 0, 0, 6, 0, 0, 0, 183, 2, 0, 0, 0, 0, 0,
        0, 123, 42, 184, 255, 0, 0, 0, 0, 123, 42, 176, 255, 0, 0, 0, 0, 123, 42, 168, 255, 0, 0,
        0, 0, 123, 42, 160, 255, 0, 0, 0, 0, 123, 42, 152, 255, 0, 0, 0, 0, 123, 42, 144, 255, 0,
        0, 0, 0, 123, 42, 136, 255, 0, 0, 0, 0, 123, 42, 128, 255, 0, 0, 0, 0, 191, 113, 0, 0, 0,
        0, 0, 0, 103, 1, 0, 0, 32, 0, 0, 0, 199, 1, 0, 0, 32, 0, 0, 0, 109, 18, 2, 0, 0, 0, 0, 0,
        183, 2, 0, 0, 64, 0, 0, 0, 45, 18, 5, 0, 0, 0, 0, 0, 24, 1, 0, 0, 158, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 183, 2, 0, 0, 28, 0, 0, 0, 191, 115, 0, 0, 0, 0, 0, 0, 5, 0, 213, 255, 0, 0, 0,
        0, 87, 7, 0, 0, 63, 0, 0, 0, 191, 161, 0, 0, 0, 0, 0, 0, 7, 1, 0, 0, 128, 255, 255, 255,
        191, 114, 0, 0, 0, 0, 0, 0, 191, 131, 0, 0, 0, 0, 0, 0, 133, 0, 0, 0, 112, 0, 0, 0, 21, 0,
        3, 0, 0, 0, 0, 0, 24, 1, 0, 0, 186, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 0, 215, 255, 0, 0,
        0, 0, 191, 163, 0, 0, 0, 0, 0, 0, 7, 3, 0, 0, 128, 255, 255, 255, 24, 1, 0, 0, 209, 1, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 183, 2, 0, 0, 35, 0, 0, 0, 191, 116, 0, 0, 0, 0, 0, 0, 133, 0,
        0, 0, 6, 0, 0, 0, 24, 1, 0, 0, 244, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 183, 2, 0, 0, 10, 0,
        0, 0, 191, 99, 0, 0, 0, 0, 0, 0, 133, 0, 0, 0, 6, 0, 0, 0, 24, 3, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 121, 161, 120, 255, 0, 0, 0, 0, 21, 1, 2, 0, 0, 0, 0, 0, 24, 3, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 24, 1, 0, 0, 254, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 183, 2,
        0, 0, 12, 0, 0, 0, 5, 0, 181, 255, 0, 0, 0, 0, 68, 117, 97, 108, 32, 66, 83, 68, 47, 71,
        80, 76, 0, 61, 61, 61, 70, 117, 110, 99, 116, 105, 111, 110, 32, 65, 114, 103, 117, 109,
        101, 110, 116, 115, 32, 61, 61, 61, 10, 0, 120, 32, 40, 105, 110, 116, 41, 32, 61, 32, 120,
        61, 37, 108, 108, 117, 10, 0, 73, 110, 118, 97, 108, 105, 100, 32, 115, 116, 114, 105, 110,
        103, 32, 108, 101, 110, 103, 116, 104, 58, 32, 37, 108, 100, 10, 0, 70, 97, 105, 108, 101,
        100, 32, 116, 111, 32, 114, 101, 97, 100, 32, 115, 116, 114, 105, 110, 103, 10, 0, 73, 110,
        116, 32, 105, 115, 58, 37, 100, 32, 97, 110, 100, 32, 83, 116, 114, 105, 110, 103, 58, 32,
        37, 115, 10, 0, 73, 110, 118, 97, 108, 105, 100, 32, 115, 116, 114, 105, 110, 103, 32, 112,
        111, 105, 110, 116, 101, 114, 32, 111, 114, 32, 108, 101, 110, 103, 116, 104, 10, 0, 78,
        117, 108, 108, 32, 112, 111, 105, 110, 116, 101, 114, 32, 114, 101, 99, 101, 105, 118, 101,
        100, 10, 0, 70, 97, 105, 108, 101, 100, 32, 116, 111, 32, 114, 101, 97, 100, 32, 65, 110,
        105, 109, 97, 108, 115, 32, 115, 116, 114, 117, 99, 116, 10, 0, 73, 110, 118, 97, 108, 105,
        100, 32, 115, 116, 114, 105, 110, 103, 32, 108, 101, 110, 103, 116, 104, 58, 32, 37, 108,
        100, 10, 0, 78, 97, 109, 101, 58, 32, 37, 115, 32, 40, 108, 101, 110, 61, 37, 108, 100, 41,
        10, 0, 73, 110, 118, 97, 108, 105, 100, 32, 115, 116, 114, 105, 110, 103, 32, 108, 101,
        110, 103, 116, 104, 58, 32, 37, 108, 100, 10, 0, 83, 112, 101, 99, 105, 101, 115, 58, 32,
        37, 115, 32, 40, 108, 101, 110, 61, 37, 108, 100, 41, 10, 0, 65, 103, 101, 58, 32, 37, 108,
        100, 10, 0, 87, 101, 105, 103, 104, 116, 58, 32, 37, 108, 102, 10, 0, 73, 115, 87, 105,
        108, 100, 58, 32, 37, 115, 10, 0, 73, 110, 118, 97, 108, 105, 100, 32, 115, 116, 114, 105,
        110, 103, 32, 108, 101, 110, 103, 116, 104, 58, 32, 37, 108, 100, 10, 0, 70, 97, 105, 108,
        101, 100, 32, 116, 111, 32, 114, 101, 97, 100, 32, 115, 116, 114, 105, 110, 103, 10, 0, 78,
        97, 109, 101, 58, 32, 37, 115, 32, 40, 108, 101, 110, 61, 37, 100, 41, 10, 0, 73, 110, 118,
        97, 108, 105, 100, 32, 115, 116, 114, 105, 110, 103, 32, 108, 101, 110, 103, 116, 104, 58,
        32, 37, 108, 100, 10, 0, 70, 97, 105, 108, 101, 100, 32, 116, 111, 32, 114, 101, 97, 100,
        32, 115, 116, 114, 105, 110, 103, 10, 0, 83, 112, 101, 99, 105, 101, 115, 32, 78, 97, 109,
        101, 58, 32, 37, 115, 32, 40, 83, 112, 101, 99, 105, 101, 115, 32, 108, 101, 110, 61, 37,
        100, 41, 10, 0, 65, 103, 101, 58, 32, 37, 108, 100, 10, 0, 73, 115, 87, 105, 108, 100, 58,
        32, 37, 115, 10, 0, 116, 114, 117, 101, 0, 102, 97, 108, 115, 101, 0, 0, 0, 0, 0, 0, 0, 8,
        0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 57, 0, 0, 0, 40, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 57, 0,
        0, 0, 144, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 57, 0, 0, 0, 192, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
        0, 57, 0, 0, 0, 24, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 57, 0, 0, 0, 120, 1, 0, 0, 0, 0, 0, 0,
        1, 0, 0, 0, 57, 0, 0, 0, 16, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 57, 0, 0, 0, 96, 0, 0, 0, 0,
        0, 0, 0, 1, 0, 0, 0, 57, 0, 0, 0, 232, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 57, 0, 0, 0, 128,
        1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 57, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 57, 0, 0,
        0, 168, 2, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 57, 0, 0, 0, 208, 2, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
        57, 0, 0, 0, 248, 2, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 57, 0, 0, 0, 24, 3, 0, 0, 0, 0, 0, 0, 1,
        0, 0, 0, 3, 0, 0, 0, 56, 3, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0, 72, 3, 0, 0, 0, 0, 0,
        0, 1, 0, 0, 0, 57, 0, 0, 0, 160, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 57, 0, 0, 0, 16, 1, 0, 0,
        0, 0, 0, 0, 1, 0, 0, 0, 57, 0, 0, 0, 80, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 57, 0, 0, 0, 240,
        1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 57, 0, 0, 0, 80, 2, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 57, 0,
        0, 0, 120, 2, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 57, 0, 0, 0, 160, 2, 0, 0, 0, 0, 0, 0, 1, 0, 0,
        0, 57, 0, 0, 0, 200, 2, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 3, 0, 0, 0, 232, 2, 0, 0, 0, 0, 0, 0,
        1, 0, 0, 0, 2, 0, 0, 0, 248, 2, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 57, 0, 0, 0, 159, 235, 1, 0,
        24, 0, 0, 0, 0, 0, 0, 0, 172, 5, 0, 0, 172, 5, 0, 0, 126, 17, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2,
        2, 0, 0, 0, 1, 0, 0, 0, 21, 0, 0, 4, 168, 0, 0, 0, 9, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 13,
        0, 0, 0, 3, 0, 0, 0, 64, 0, 0, 0, 17, 0, 0, 0, 3, 0, 0, 0, 128, 0, 0, 0, 21, 0, 0, 0, 3, 0,
        0, 0, 192, 0, 0, 0, 25, 0, 0, 0, 3, 0, 0, 0, 0, 1, 0, 0, 28, 0, 0, 0, 3, 0, 0, 0, 64, 1, 0,
        0, 31, 0, 0, 0, 3, 0, 0, 0, 128, 1, 0, 0, 35, 0, 0, 0, 3, 0, 0, 0, 192, 1, 0, 0, 39, 0, 0,
        0, 3, 0, 0, 0, 0, 2, 0, 0, 42, 0, 0, 0, 3, 0, 0, 0, 64, 2, 0, 0, 45, 0, 0, 0, 3, 0, 0, 0,
        128, 2, 0, 0, 48, 0, 0, 0, 3, 0, 0, 0, 192, 2, 0, 0, 51, 0, 0, 0, 3, 0, 0, 0, 0, 3, 0, 0,
        54, 0, 0, 0, 3, 0, 0, 0, 64, 3, 0, 0, 57, 0, 0, 0, 3, 0, 0, 0, 128, 3, 0, 0, 60, 0, 0, 0,
        3, 0, 0, 0, 192, 3, 0, 0, 68, 0, 0, 0, 3, 0, 0, 0, 0, 4, 0, 0, 71, 0, 0, 0, 3, 0, 0, 0, 64,
        4, 0, 0, 74, 0, 0, 0, 3, 0, 0, 0, 128, 4, 0, 0, 80, 0, 0, 0, 3, 0, 0, 0, 192, 4, 0, 0, 83,
        0, 0, 0, 3, 0, 0, 0, 0, 5, 0, 0, 86, 0, 0, 0, 0, 0, 0, 1, 8, 0, 0, 0, 64, 0, 0, 0, 0, 0, 0,
        0, 1, 0, 0, 13, 5, 0, 0, 0, 104, 0, 0, 0, 1, 0, 0, 0, 108, 0, 0, 0, 0, 0, 0, 1, 4, 0, 0, 0,
        32, 0, 0, 1, 112, 0, 0, 0, 1, 0, 0, 12, 4, 0, 0, 0, 129, 0, 0, 0, 1, 0, 0, 12, 4, 0, 0, 0,
        153, 0, 0, 0, 1, 0, 0, 12, 4, 0, 0, 0, 181, 0, 0, 0, 1, 0, 0, 12, 4, 0, 0, 0, 207, 0, 0, 0,
        0, 0, 0, 1, 1, 0, 0, 0, 8, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 10, 0, 0, 0, 12, 0,
        0, 0, 13, 0, 0, 0, 212, 0, 0, 0, 0, 0, 0, 1, 4, 0, 0, 0, 32, 0, 0, 0, 232, 0, 0, 0, 0, 0,
        0, 14, 11, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10, 10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        3, 0, 0, 0, 0, 14, 0, 0, 0, 12, 0, 0, 0, 27, 0, 0, 0, 240, 0, 0, 0, 0, 0, 0, 14, 15, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 14, 0, 0, 0, 12, 0, 0, 0, 18, 0, 0, 0,
        9, 1, 0, 0, 0, 0, 0, 14, 17, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 14,
        0, 0, 0, 12, 0, 0, 0, 28, 0, 0, 0, 36, 1, 0, 0, 0, 0, 0, 14, 19, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 14, 0, 0, 0, 12, 0, 0, 0, 23, 0, 0, 0, 68, 1, 0, 0, 0, 0, 0,
        14, 21, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 14, 0, 0, 0, 12, 0, 0, 0,
        26, 0, 0, 0, 102, 1, 0, 0, 0, 0, 0, 14, 23, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0,
        0, 0, 0, 14, 0, 0, 0, 12, 0, 0, 0, 34, 0, 0, 0, 136, 1, 0, 0, 0, 0, 0, 14, 25, 0, 0, 0, 0,
        0, 0, 0, 170, 1, 0, 0, 0, 0, 0, 14, 21, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0,
        0, 0, 14, 0, 0, 0, 12, 0, 0, 0, 31, 0, 0, 0, 206, 1, 0, 0, 0, 0, 0, 14, 28, 0, 0, 0, 0, 0,
        0, 0, 244, 1, 0, 0, 0, 0, 0, 14, 19, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0,
        0, 14, 0, 0, 0, 12, 0, 0, 0, 20, 0, 0, 0, 26, 2, 0, 0, 0, 0, 0, 14, 31, 0, 0, 0, 0, 0, 0,
        0, 64, 2, 0, 0, 0, 0, 0, 14, 19, 0, 0, 0, 0, 0, 0, 0, 102, 2, 0, 0, 0, 0, 0, 14, 21, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 14, 0, 0, 0, 12, 0, 0, 0, 10, 0, 0, 0,
        140, 2, 0, 0, 0, 0, 0, 14, 35, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 14,
        0, 0, 0, 12, 0, 0, 0, 13, 0, 0, 0, 179, 2, 0, 0, 0, 0, 0, 14, 37, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 14, 0, 0, 0, 12, 0, 0, 0, 12, 0, 0, 0, 218, 2, 0, 0, 0, 0,
        0, 14, 39, 0, 0, 0, 0, 0, 0, 0, 1, 3, 0, 0, 0, 0, 0, 14, 19, 0, 0, 0, 0, 0, 0, 0, 35, 3, 0,
        0, 0, 0, 0, 14, 21, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 14, 0, 0, 0,
        12, 0, 0, 0, 19, 0, 0, 0, 72, 3, 0, 0, 0, 0, 0, 14, 43, 0, 0, 0, 0, 0, 0, 0, 109, 3, 0, 0,
        0, 0, 0, 14, 19, 0, 0, 0, 0, 0, 0, 0, 146, 3, 0, 0, 0, 0, 0, 14, 21, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 14, 0, 0, 0, 12, 0, 0, 0, 35, 0, 0, 0, 183, 3, 0, 0, 0,
        0, 0, 14, 47, 0, 0, 0, 0, 0, 0, 0, 220, 3, 0, 0, 0, 0, 0, 14, 35, 0, 0, 0, 0, 0, 0, 0, 1,
        4, 0, 0, 0, 0, 0, 14, 39, 0, 0, 0, 0, 0, 0, 0, 247, 16, 0, 0, 1, 0, 0, 15, 13, 0, 0, 0, 13,
        0, 0, 0, 0, 0, 0, 0, 13, 0, 0, 0, 255, 16, 0, 0, 23, 0, 0, 15, 10, 2, 0, 0, 16, 0, 0, 0, 0,
        0, 0, 0, 27, 0, 0, 0, 18, 0, 0, 0, 27, 0, 0, 0, 18, 0, 0, 0, 20, 0, 0, 0, 45, 0, 0, 0, 28,
        0, 0, 0, 22, 0, 0, 0, 73, 0, 0, 0, 23, 0, 0, 0, 24, 0, 0, 0, 96, 0, 0, 0, 26, 0, 0, 0, 26,
        0, 0, 0, 122, 0, 0, 0, 34, 0, 0, 0, 27, 0, 0, 0, 156, 0, 0, 0, 23, 0, 0, 0, 29, 0, 0, 0,
        179, 0, 0, 0, 31, 0, 0, 0, 30, 0, 0, 0, 210, 0, 0, 0, 28, 0, 0, 0, 32, 0, 0, 0, 238, 0, 0,
        0, 20, 0, 0, 0, 33, 0, 0, 0, 2, 1, 0, 0, 28, 0, 0, 0, 34, 0, 0, 0, 30, 1, 0, 0, 23, 0, 0,
        0, 36, 0, 0, 0, 53, 1, 0, 0, 10, 0, 0, 0, 38, 0, 0, 0, 63, 1, 0, 0, 13, 0, 0, 0, 40, 0, 0,
        0, 76, 1, 0, 0, 12, 0, 0, 0, 41, 0, 0, 0, 88, 1, 0, 0, 28, 0, 0, 0, 42, 0, 0, 0, 116, 1, 0,
        0, 23, 0, 0, 0, 44, 0, 0, 0, 139, 1, 0, 0, 19, 0, 0, 0, 45, 0, 0, 0, 158, 1, 0, 0, 28, 0,
        0, 0, 46, 0, 0, 0, 186, 1, 0, 0, 23, 0, 0, 0, 48, 0, 0, 0, 209, 1, 0, 0, 35, 0, 0, 0, 49,
        0, 0, 0, 244, 1, 0, 0, 10, 0, 0, 0, 50, 0, 0, 0, 254, 1, 0, 0, 12, 0, 0, 0, 0, 112, 116,
        95, 114, 101, 103, 115, 0, 114, 49, 53, 0, 114, 49, 52, 0, 114, 49, 51, 0, 114, 49, 50, 0,
        98, 112, 0, 98, 120, 0, 114, 49, 49, 0, 114, 49, 48, 0, 114, 57, 0, 114, 56, 0, 97, 120, 0,
        99, 120, 0, 100, 120, 0, 115, 105, 0, 100, 105, 0, 111, 114, 105, 103, 95, 97, 120, 0, 105,
        112, 0, 99, 115, 0, 102, 108, 97, 103, 115, 0, 115, 112, 0, 115, 115, 0, 108, 111, 110,
        103, 32, 117, 110, 115, 105, 103, 110, 101, 100, 32, 105, 110, 116, 0, 99, 116, 120, 0,
        105, 110, 116, 0, 104, 97, 110, 100, 108, 101, 95, 104, 101, 108, 108, 111, 95, 105, 110,
        116, 0, 104, 97, 110, 100, 108, 101, 95, 104, 101, 108, 108, 111, 95, 105, 110, 116, 95,
        115, 116, 114, 105, 110, 103, 0, 104, 97, 110, 100, 108, 101, 95, 104, 101, 108, 108, 111,
        95, 115, 116, 114, 117, 99, 116, 95, 112, 111, 105, 110, 116, 101, 114, 0, 104, 97, 110,
        100, 108, 101, 95, 104, 101, 108, 108, 111, 95, 115, 116, 114, 117, 99, 116, 95, 118, 97,
        108, 117, 101, 0, 99, 104, 97, 114, 0, 95, 95, 65, 82, 82, 65, 89, 95, 83, 73, 90, 69, 95,
        84, 89, 80, 69, 95, 95, 0, 76, 73, 67, 69, 78, 83, 69, 0, 104, 97, 110, 100, 108, 101, 95,
        104, 101, 108, 108, 111, 95, 105, 110, 116, 46, 95, 95, 95, 95, 102, 109, 116, 0, 104, 97,
        110, 100, 108, 101, 95, 104, 101, 108, 108, 111, 95, 105, 110, 116, 46, 95, 95, 95, 95,
        102, 109, 116, 46, 49, 0, 104, 97, 110, 100, 108, 101, 95, 104, 101, 108, 108, 111, 95,
        105, 110, 116, 95, 115, 116, 114, 105, 110, 103, 46, 95, 95, 95, 95, 102, 109, 116, 0, 104,
        97, 110, 100, 108, 101, 95, 104, 101, 108, 108, 111, 95, 105, 110, 116, 95, 115, 116, 114,
        105, 110, 103, 46, 95, 95, 95, 95, 102, 109, 116, 46, 50, 0, 104, 97, 110, 100, 108, 101,
        95, 104, 101, 108, 108, 111, 95, 105, 110, 116, 95, 115, 116, 114, 105, 110, 103, 46, 95,
        95, 95, 95, 102, 109, 116, 46, 51, 0, 104, 97, 110, 100, 108, 101, 95, 104, 101, 108, 108,
        111, 95, 105, 110, 116, 95, 115, 116, 114, 105, 110, 103, 46, 95, 95, 95, 95, 102, 109,
        116, 46, 52, 0, 104, 97, 110, 100, 108, 101, 95, 104, 101, 108, 108, 111, 95, 115, 116,
        114, 117, 99, 116, 95, 112, 111, 105, 110, 116, 101, 114, 46, 95, 95, 95, 95, 102, 109,
        116, 0, 104, 97, 110, 100, 108, 101, 95, 104, 101, 108, 108, 111, 95, 115, 116, 114, 117,
        99, 116, 95, 112, 111, 105, 110, 116, 101, 114, 46, 95, 95, 95, 95, 102, 109, 116, 46, 53,
        0, 104, 97, 110, 100, 108, 101, 95, 104, 101, 108, 108, 111, 95, 115, 116, 114, 117, 99,
        116, 95, 112, 111, 105, 110, 116, 101, 114, 46, 95, 95, 95, 95, 102, 109, 116, 46, 54, 0,
        104, 97, 110, 100, 108, 101, 95, 104, 101, 108, 108, 111, 95, 115, 116, 114, 117, 99, 116,
        95, 112, 111, 105, 110, 116, 101, 114, 46, 95, 95, 95, 95, 102, 109, 116, 46, 55, 0, 104,
        97, 110, 100, 108, 101, 95, 104, 101, 108, 108, 111, 95, 115, 116, 114, 117, 99, 116, 95,
        112, 111, 105, 110, 116, 101, 114, 46, 95, 95, 95, 95, 102, 109, 116, 46, 56, 0, 104, 97,
        110, 100, 108, 101, 95, 104, 101, 108, 108, 111, 95, 115, 116, 114, 117, 99, 116, 95, 112,
        111, 105, 110, 116, 101, 114, 46, 95, 95, 95, 95, 102, 109, 116, 46, 57, 0, 104, 97, 110,
        100, 108, 101, 95, 104, 101, 108, 108, 111, 95, 115, 116, 114, 117, 99, 116, 95, 112, 111,
        105, 110, 116, 101, 114, 46, 95, 95, 95, 95, 102, 109, 116, 46, 49, 48, 0, 104, 97, 110,
        100, 108, 101, 95, 104, 101, 108, 108, 111, 95, 115, 116, 114, 117, 99, 116, 95, 112, 111,
        105, 110, 116, 101, 114, 46, 95, 95, 95, 95, 102, 109, 116, 46, 49, 49, 0, 104, 97, 110,
        100, 108, 101, 95, 104, 101, 108, 108, 111, 95, 115, 116, 114, 117, 99, 116, 95, 112, 111,
        105, 110, 116, 101, 114, 46, 95, 95, 95, 95, 102, 109, 116, 46, 49, 50, 0, 104, 97, 110,
        100, 108, 101, 95, 104, 101, 108, 108, 111, 95, 115, 116, 114, 117, 99, 116, 95, 118, 97,
        108, 117, 101, 46, 95, 95, 95, 95, 102, 109, 116, 0, 104, 97, 110, 100, 108, 101, 95, 104,
        101, 108, 108, 111, 95, 115, 116, 114, 117, 99, 116, 95, 118, 97, 108, 117, 101, 46, 95,
        95, 95, 95, 102, 109, 116, 46, 49, 52, 0, 104, 97, 110, 100, 108, 101, 95, 104, 101, 108,
        108, 111, 95, 115, 116, 114, 117, 99, 116, 95, 118, 97, 108, 117, 101, 46, 95, 95, 95, 95,
        102, 109, 116, 46, 49, 53, 0, 104, 97, 110, 100, 108, 101, 95, 104, 101, 108, 108, 111, 95,
        115, 116, 114, 117, 99, 116, 95, 118, 97, 108, 117, 101, 46, 95, 95, 95, 95, 102, 109, 116,
        46, 49, 54, 0, 104, 97, 110, 100, 108, 101, 95, 104, 101, 108, 108, 111, 95, 115, 116, 114,
        117, 99, 116, 95, 118, 97, 108, 117, 101, 46, 95, 95, 95, 95, 102, 109, 116, 46, 49, 55, 0,
        104, 97, 110, 100, 108, 101, 95, 104, 101, 108, 108, 111, 95, 115, 116, 114, 117, 99, 116,
        95, 118, 97, 108, 117, 101, 46, 95, 95, 95, 95, 102, 109, 116, 46, 49, 56, 0, 104, 97, 110,
        100, 108, 101, 95, 104, 101, 108, 108, 111, 95, 115, 116, 114, 117, 99, 116, 95, 118, 97,
        108, 117, 101, 46, 95, 95, 95, 95, 102, 109, 116, 46, 49, 57, 0, 104, 97, 110, 100, 108,
        101, 95, 104, 101, 108, 108, 111, 95, 115, 116, 114, 117, 99, 116, 95, 118, 97, 108, 117,
        101, 46, 95, 95, 95, 95, 102, 109, 116, 46, 50, 48, 0, 47, 112, 114, 111, 106, 101, 99,
        116, 47, 115, 114, 99, 47, 98, 112, 102, 47, 103, 111, 46, 98, 112, 102, 46, 99, 0, 32, 32,
        32, 32, 105, 110, 116, 32, 120, 32, 61, 32, 40, 105, 110, 116, 41, 99, 116, 120, 45, 62,
        97, 120, 59, 0, 32, 32, 32, 32, 98, 112, 102, 95, 112, 114, 105, 110, 116, 107, 40, 34, 61,
        61, 61, 70, 117, 110, 99, 116, 105, 111, 110, 32, 65, 114, 103, 117, 109, 101, 110, 116,
        115, 32, 61, 61, 61, 92, 110, 34, 41, 59, 0, 32, 32, 32, 32, 98, 112, 102, 95, 112, 114,
        105, 110, 116, 107, 40, 34, 120, 32, 40, 105, 110, 116, 41, 32, 61, 32, 120, 61, 37, 108,
        108, 117, 92, 110, 34, 44, 32, 120, 41, 59, 0, 32, 32, 32, 32, 114, 101, 116, 117, 114,
        110, 32, 48, 59, 0, 32, 32, 32, 32, 118, 111, 105, 100, 32, 42, 115, 116, 114, 95, 112,
        116, 114, 32, 61, 32, 40, 118, 111, 105, 100, 32, 42, 41, 99, 116, 120, 45, 62, 98, 120,
        59, 32, 47, 47, 32, 83, 116, 114, 105, 110, 103, 32, 100, 97, 116, 97, 32, 112, 111, 105,
        110, 116, 101, 114, 0, 32, 32, 32, 32, 105, 102, 32, 40, 115, 116, 114, 95, 112, 116, 114,
        32, 33, 61, 32, 78, 85, 76, 76, 32, 38, 38, 32, 115, 116, 114, 95, 108, 101, 110, 95, 114,
        97, 119, 32, 62, 32, 48, 41, 0, 32, 32, 32, 32, 32, 32, 32, 32, 99, 104, 97, 114, 32, 115,
        116, 114, 95, 98, 117, 102, 91, 77, 65, 88, 95, 83, 84, 82, 73, 78, 71, 95, 76, 69, 78, 32,
        43, 32, 49, 93, 32, 61, 32, 123, 48, 125, 59, 0, 32, 32, 32, 32, 32, 32, 32, 32, 105, 102,
        32, 40, 115, 116, 114, 95, 108, 101, 110, 95, 114, 97, 119, 32, 60, 32, 48, 32, 124, 124,
        32, 115, 116, 114, 95, 108, 101, 110, 95, 114, 97, 119, 32, 62, 32, 115, 105, 122, 101,
        111, 102, 40, 115, 116, 114, 95, 98, 117, 102, 41, 41, 0, 32, 32, 32, 32, 32, 32, 32, 32,
        32, 32, 32, 32, 98, 112, 102, 95, 112, 114, 105, 110, 116, 107, 40, 34, 73, 110, 118, 97,
        108, 105, 100, 32, 115, 116, 114, 105, 110, 103, 32, 108, 101, 110, 103, 116, 104, 58, 32,
        37, 108, 100, 92, 110, 34, 44, 32, 115, 116, 114, 95, 108, 101, 110, 95, 114, 97, 119, 41,
        59, 0, 32, 32, 32, 32, 32, 32, 32, 32, 98, 112, 102, 95, 112, 114, 105, 110, 116, 107, 40,
        34, 73, 110, 118, 97, 108, 105, 100, 32, 115, 116, 114, 105, 110, 103, 32, 112, 111, 105,
        110, 116, 101, 114, 32, 111, 114, 32, 108, 101, 110, 103, 116, 104, 92, 110, 34, 41, 59, 0,
        125, 0, 32, 32, 32, 32, 32, 32, 32, 32, 108, 111, 110, 103, 32, 114, 101, 116, 32, 61, 32,
        98, 112, 102, 95, 112, 114, 111, 98, 101, 95, 114, 101, 97, 100, 95, 117, 115, 101, 114,
        40, 115, 116, 114, 95, 98, 117, 102, 44, 32, 115, 116, 114, 95, 108, 101, 110, 95, 114, 97,
        119, 44, 32, 115, 116, 114, 95, 112, 116, 114, 41, 59, 0, 32, 32, 32, 32, 32, 32, 32, 32,
        105, 102, 32, 40, 114, 101, 116, 32, 60, 32, 48, 41, 0, 32, 32, 32, 32, 32, 32, 32, 32, 32,
        32, 32, 32, 98, 112, 102, 95, 112, 114, 105, 110, 116, 107, 40, 34, 70, 97, 105, 108, 101,
        100, 32, 116, 111, 32, 114, 101, 97, 100, 32, 115, 116, 114, 105, 110, 103, 92, 110, 34,
        41, 59, 0, 32, 32, 32, 32, 32, 32, 32, 32, 105, 102, 32, 40, 115, 116, 114, 95, 108, 101,
        110, 95, 114, 97, 119, 32, 60, 32, 115, 105, 122, 101, 111, 102, 40, 115, 116, 114, 95, 98,
        117, 102, 41, 41, 0, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 115, 116, 114, 95, 98,
        117, 102, 91, 115, 116, 114, 95, 108, 101, 110, 95, 114, 97, 119, 93, 32, 61, 32, 39, 92,
        48, 39, 59, 0, 32, 32, 32, 32, 32, 32, 32, 32, 98, 112, 102, 95, 112, 114, 105, 110, 116,
        107, 40, 34, 73, 110, 116, 32, 105, 115, 58, 37, 100, 32, 97, 110, 100, 32, 83, 116, 114,
        105, 110, 103, 58, 32, 37, 115, 92, 110, 34, 44, 32, 120, 44, 32, 115, 116, 114, 95, 98,
        117, 102, 41, 59, 0, 32, 32, 32, 32, 118, 111, 105, 100, 32, 42, 97, 110, 105, 109, 97,
        108, 115, 95, 112, 116, 114, 32, 61, 32, 40, 118, 111, 105, 100, 32, 42, 41, 80, 84, 95,
        82, 69, 71, 83, 95, 82, 67, 40, 99, 116, 120, 41, 59, 32, 47, 47, 32, 82, 65, 88, 32, 114,
        101, 103, 105, 115, 116, 101, 114, 0, 32, 32, 32, 32, 105, 102, 32, 40, 33, 97, 110, 105,
        109, 97, 108, 115, 95, 112, 116, 114, 41, 0, 32, 32, 32, 32, 32, 32, 32, 32, 98, 112, 102,
        95, 112, 114, 105, 110, 116, 107, 40, 34, 78, 117, 108, 108, 32, 112, 111, 105, 110, 116,
        101, 114, 32, 114, 101, 99, 101, 105, 118, 101, 100, 92, 110, 34, 41, 59, 0, 32, 32, 32,
        32, 105, 102, 32, 40, 98, 112, 102, 95, 112, 114, 111, 98, 101, 95, 114, 101, 97, 100, 95,
        117, 115, 101, 114, 40, 38, 97, 110, 105, 109, 97, 108, 115, 44, 32, 115, 105, 122, 101,
        111, 102, 40, 97, 110, 105, 109, 97, 108, 115, 41, 44, 32, 97, 110, 105, 109, 97, 108, 115,
        95, 112, 116, 114, 41, 32, 33, 61, 32, 48, 41, 0, 32, 32, 32, 32, 32, 32, 32, 32, 98, 112,
        102, 95, 112, 114, 105, 110, 116, 107, 40, 34, 70, 97, 105, 108, 101, 100, 32, 116, 111,
        32, 114, 101, 97, 100, 32, 65, 110, 105, 109, 97, 108, 115, 32, 115, 116, 114, 117, 99,
        116, 92, 110, 34, 41, 59, 0, 32, 32, 32, 32, 99, 104, 97, 114, 32, 110, 97, 109, 101, 95,
        98, 117, 102, 91, 54, 52, 93, 32, 61, 32, 123, 48, 125, 59, 0, 32, 32, 32, 32, 108, 111,
        110, 103, 32, 115, 116, 114, 95, 108, 101, 110, 95, 114, 97, 119, 32, 61, 32, 97, 110, 105,
        109, 97, 108, 115, 46, 110, 97, 109, 101, 95, 108, 101, 110, 59, 0, 32, 32, 32, 32, 105,
        102, 32, 40, 115, 116, 114, 95, 108, 101, 110, 95, 114, 97, 119, 32, 60, 32, 48, 32, 124,
        124, 32, 115, 116, 114, 95, 108, 101, 110, 95, 114, 97, 119, 32, 62, 32, 115, 105, 122,
        101, 111, 102, 40, 110, 97, 109, 101, 95, 98, 117, 102, 41, 41, 0, 32, 32, 32, 32, 32, 32,
        32, 32, 98, 112, 102, 95, 112, 114, 105, 110, 116, 107, 40, 34, 73, 110, 118, 97, 108, 105,
        100, 32, 115, 116, 114, 105, 110, 103, 32, 108, 101, 110, 103, 116, 104, 58, 32, 37, 108,
        100, 92, 110, 34, 44, 32, 115, 116, 114, 95, 108, 101, 110, 95, 114, 97, 119, 41, 59, 0,
        32, 32, 32, 32, 105, 102, 32, 40, 97, 110, 105, 109, 97, 108, 115, 46, 110, 97, 109, 101,
        95, 108, 101, 110, 32, 62, 32, 48, 32, 38, 38, 32, 97, 110, 105, 109, 97, 108, 115, 46,
        110, 97, 109, 101, 95, 108, 101, 110, 32, 60, 32, 115, 105, 122, 101, 111, 102, 40, 110,
        97, 109, 101, 95, 98, 117, 102, 41, 41, 0, 32, 32, 32, 32, 32, 32, 32, 32, 105, 102, 32,
        40, 98, 112, 102, 95, 112, 114, 111, 98, 101, 95, 114, 101, 97, 100, 95, 117, 115, 101,
        114, 40, 110, 97, 109, 101, 95, 98, 117, 102, 44, 32, 115, 116, 114, 95, 108, 101, 110, 95,
        114, 97, 119, 44, 32, 97, 110, 105, 109, 97, 108, 115, 46, 110, 97, 109, 101, 95, 112, 116,
        114, 41, 32, 61, 61, 32, 48, 41, 0, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 110,
        97, 109, 101, 95, 98, 117, 102, 91, 115, 116, 114, 95, 108, 101, 110, 95, 114, 97, 119, 93,
        32, 61, 32, 39, 92, 48, 39, 59, 0, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 98, 112,
        102, 95, 112, 114, 105, 110, 116, 107, 40, 34, 78, 97, 109, 101, 58, 32, 37, 115, 32, 40,
        108, 101, 110, 61, 37, 108, 100, 41, 92, 110, 34, 44, 32, 110, 97, 109, 101, 95, 98, 117,
        102, 44, 32, 97, 110, 105, 109, 97, 108, 115, 46, 110, 97, 109, 101, 95, 108, 101, 110, 41,
        59, 0, 32, 32, 32, 32, 99, 104, 97, 114, 32, 115, 112, 101, 99, 105, 101, 115, 95, 98, 117,
        102, 91, 54, 52, 93, 32, 61, 32, 123, 48, 125, 59, 0, 32, 32, 32, 32, 108, 111, 110, 103,
        32, 115, 116, 114, 95, 108, 101, 110, 95, 115, 112, 101, 99, 105, 101, 115, 95, 114, 97,
        119, 32, 61, 32, 97, 110, 105, 109, 97, 108, 115, 46, 115, 112, 101, 99, 105, 101, 115, 95,
        108, 101, 110, 59, 0, 32, 32, 32, 32, 105, 102, 32, 40, 115, 116, 114, 95, 108, 101, 110,
        95, 115, 112, 101, 99, 105, 101, 115, 95, 114, 97, 119, 32, 60, 32, 48, 32, 124, 124, 32,
        115, 116, 114, 95, 108, 101, 110, 95, 115, 112, 101, 99, 105, 101, 115, 95, 114, 97, 119,
        32, 62, 32, 115, 105, 122, 101, 111, 102, 40, 110, 97, 109, 101, 95, 98, 117, 102, 41, 41,
        0, 32, 32, 32, 32, 32, 32, 32, 32, 98, 112, 102, 95, 112, 114, 105, 110, 116, 107, 40, 34,
        73, 110, 118, 97, 108, 105, 100, 32, 115, 116, 114, 105, 110, 103, 32, 108, 101, 110, 103,
        116, 104, 58, 32, 37, 108, 100, 92, 110, 34, 44, 32, 115, 116, 114, 95, 108, 101, 110, 95,
        115, 112, 101, 99, 105, 101, 115, 95, 114, 97, 119, 41, 59, 0, 32, 32, 32, 32, 105, 102,
        32, 40, 97, 110, 105, 109, 97, 108, 115, 46, 115, 112, 101, 99, 105, 101, 115, 95, 108,
        101, 110, 32, 62, 32, 48, 32, 38, 38, 32, 97, 110, 105, 109, 97, 108, 115, 46, 115, 112,
        101, 99, 105, 101, 115, 95, 108, 101, 110, 32, 60, 32, 115, 105, 122, 101, 111, 102, 40,
        115, 112, 101, 99, 105, 101, 115, 95, 98, 117, 102, 41, 41, 0, 32, 32, 32, 32, 32, 32, 32,
        32, 105, 102, 32, 40, 98, 112, 102, 95, 112, 114, 111, 98, 101, 95, 114, 101, 97, 100, 95,
        117, 115, 101, 114, 40, 115, 112, 101, 99, 105, 101, 115, 95, 98, 117, 102, 44, 32, 115,
        116, 114, 95, 108, 101, 110, 95, 115, 112, 101, 99, 105, 101, 115, 95, 114, 97, 119, 44,
        32, 97, 110, 105, 109, 97, 108, 115, 46, 115, 112, 101, 99, 105, 101, 115, 95, 112, 116,
        114, 41, 32, 61, 61, 32, 48, 41, 0, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 115,
        112, 101, 99, 105, 101, 115, 95, 98, 117, 102, 91, 115, 116, 114, 95, 108, 101, 110, 95,
        115, 112, 101, 99, 105, 101, 115, 95, 114, 97, 119, 93, 32, 61, 32, 39, 92, 48, 39, 59, 0,
        32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 98, 112, 102, 95, 112, 114, 105, 110, 116,
        107, 40, 34, 83, 112, 101, 99, 105, 101, 115, 58, 32, 37, 115, 32, 40, 108, 101, 110, 61,
        37, 108, 100, 41, 92, 110, 34, 44, 32, 115, 112, 101, 99, 105, 101, 115, 95, 98, 117, 102,
        44, 32, 97, 110, 105, 109, 97, 108, 115, 46, 115, 112, 101, 99, 105, 101, 115, 95, 108,
        101, 110, 41, 59, 0, 32, 32, 32, 32, 98, 112, 102, 95, 112, 114, 105, 110, 116, 107, 40,
        34, 65, 103, 101, 58, 32, 37, 108, 100, 92, 110, 34, 44, 32, 97, 110, 105, 109, 97, 108,
        115, 46, 97, 103, 101, 41, 59, 0, 32, 32, 32, 32, 98, 112, 102, 95, 112, 114, 105, 110,
        116, 107, 40, 34, 87, 101, 105, 103, 104, 116, 58, 32, 37, 108, 102, 92, 110, 34, 44, 32,
        97, 110, 105, 109, 97, 108, 115, 46, 119, 101, 105, 103, 104, 116, 41, 59, 0, 32, 32, 32,
        32, 98, 112, 102, 95, 112, 114, 105, 110, 116, 107, 40, 34, 73, 115, 87, 105, 108, 100, 58,
        32, 37, 115, 92, 110, 34, 44, 32, 97, 110, 105, 109, 97, 108, 115, 46, 105, 115, 95, 119,
        105, 108, 100, 32, 63, 32, 34, 116, 114, 117, 101, 34, 32, 58, 32, 34, 102, 97, 108, 115,
        101, 34, 41, 59, 0, 32, 32, 32, 32, 108, 111, 110, 103, 32, 105, 115, 95, 119, 105, 108,
        100, 32, 61, 32, 40, 108, 111, 110, 103, 41, 99, 116, 120, 45, 62, 114, 56, 59, 32, 47, 47,
        32, 82, 56, 0, 32, 32, 32, 32, 108, 111, 110, 103, 32, 97, 103, 101, 32, 61, 32, 40, 108,
        111, 110, 103, 41, 99, 116, 120, 45, 62, 115, 105, 59, 32, 32, 32, 32, 32, 47, 47, 32, 82,
        83, 73, 0, 32, 32, 32, 32, 108, 111, 110, 103, 32, 115, 112, 101, 99, 105, 101, 115, 95,
        108, 101, 110, 32, 61, 32, 40, 108, 111, 110, 103, 41, 99, 116, 120, 45, 62, 100, 105, 59,
        32, 32, 32, 32, 32, 32, 32, 32, 32, 47, 47, 32, 82, 68, 73, 0, 32, 32, 32, 32, 118, 111,
        105, 100, 32, 42, 110, 97, 109, 101, 95, 112, 116, 114, 32, 61, 32, 40, 118, 111, 105, 100,
        32, 42, 41, 80, 84, 95, 82, 69, 71, 83, 95, 82, 67, 40, 99, 116, 120, 41, 59, 32, 47, 47,
        32, 82, 65, 88, 0, 32, 32, 32, 32, 108, 111, 110, 103, 32, 110, 97, 109, 101, 95, 108, 101,
        110, 32, 61, 32, 40, 108, 111, 110, 103, 41, 99, 116, 120, 45, 62, 98, 120, 59, 32, 32, 32,
        32, 32, 32, 32, 32, 32, 32, 32, 32, 47, 47, 32, 82, 66, 88, 0, 32, 32, 32, 32, 105, 110,
        116, 32, 115, 116, 114, 95, 108, 101, 110, 95, 114, 97, 119, 32, 61, 32, 110, 97, 109, 101,
        95, 108, 101, 110, 59, 0, 32, 32, 32, 32, 105, 102, 32, 40, 115, 116, 114, 95, 108, 101,
        110, 95, 114, 97, 119, 32, 60, 32, 48, 32, 124, 124, 32, 115, 116, 114, 95, 108, 101, 110,
        95, 114, 97, 119, 32, 62, 61, 32, 115, 105, 122, 101, 111, 102, 40, 110, 97, 109, 101, 95,
        98, 117, 102, 41, 41, 0, 32, 32, 32, 32, 115, 97, 102, 101, 95, 108, 101, 110, 32, 38, 61,
        32, 48, 120, 51, 70, 59, 32, 47, 47, 32, 77, 97, 115, 107, 32, 116, 111, 32, 101, 110, 115,
        117, 114, 101, 32, 105, 116, 39, 115, 32, 60, 61, 32, 54, 51, 32, 40, 48, 120, 51, 70, 32,
        61, 32, 54, 51, 41, 0, 32, 32, 32, 32, 105, 102, 32, 40, 98, 112, 102, 95, 112, 114, 111,
        98, 101, 95, 114, 101, 97, 100, 95, 117, 115, 101, 114, 40, 110, 97, 109, 101, 95, 98, 117,
        102, 44, 32, 115, 97, 102, 101, 95, 108, 101, 110, 44, 32, 110, 97, 109, 101, 95, 112, 116,
        114, 41, 32, 33, 61, 32, 48, 41, 0, 32, 32, 32, 32, 32, 32, 32, 32, 98, 112, 102, 95, 112,
        114, 105, 110, 116, 107, 40, 34, 70, 97, 105, 108, 101, 100, 32, 116, 111, 32, 114, 101,
        97, 100, 32, 115, 116, 114, 105, 110, 103, 92, 110, 34, 41, 59, 0, 32, 32, 32, 32, 98, 112,
        102, 95, 112, 114, 105, 110, 116, 107, 40, 34, 78, 97, 109, 101, 58, 32, 37, 115, 32, 40,
        108, 101, 110, 61, 37, 100, 41, 92, 110, 34, 44, 32, 110, 97, 109, 101, 95, 98, 117, 102,
        44, 32, 115, 97, 102, 101, 95, 108, 101, 110, 41, 59, 0, 32, 32, 32, 32, 105, 110, 116, 32,
        115, 112, 101, 95, 115, 116, 114, 95, 108, 101, 110, 95, 114, 97, 119, 32, 61, 32, 115,
        112, 101, 99, 105, 101, 115, 95, 108, 101, 110, 59, 0, 32, 32, 32, 32, 105, 102, 32, 40,
        115, 112, 101, 95, 115, 116, 114, 95, 108, 101, 110, 95, 114, 97, 119, 32, 60, 32, 48, 32,
        124, 124, 32, 115, 112, 101, 95, 115, 116, 114, 95, 108, 101, 110, 95, 114, 97, 119, 32,
        62, 61, 32, 115, 105, 122, 101, 111, 102, 40, 115, 112, 101, 99, 105, 101, 115, 95, 98,
        117, 102, 41, 41, 0, 32, 32, 32, 32, 32, 32, 32, 32, 98, 112, 102, 95, 112, 114, 105, 110,
        116, 107, 40, 34, 73, 110, 118, 97, 108, 105, 100, 32, 115, 116, 114, 105, 110, 103, 32,
        108, 101, 110, 103, 116, 104, 58, 32, 37, 108, 100, 92, 110, 34, 44, 32, 115, 112, 101, 95,
        115, 116, 114, 95, 108, 101, 110, 95, 114, 97, 119, 41, 59, 0, 32, 32, 32, 32, 115, 112,
        101, 99, 105, 101, 115, 95, 115, 97, 102, 101, 95, 108, 101, 110, 32, 38, 61, 32, 48, 120,
        51, 70, 59, 32, 47, 47, 32, 77, 97, 115, 107, 32, 116, 111, 32, 101, 110, 115, 117, 114,
        101, 32, 105, 116, 39, 115, 32, 60, 61, 32, 54, 51, 32, 40, 48, 120, 51, 70, 32, 61, 32,
        54, 51, 41, 0, 32, 32, 32, 32, 105, 102, 32, 40, 98, 112, 102, 95, 112, 114, 111, 98, 101,
        95, 114, 101, 97, 100, 95, 117, 115, 101, 114, 40, 115, 112, 101, 99, 105, 101, 115, 95,
        98, 117, 102, 44, 32, 115, 112, 101, 99, 105, 101, 115, 95, 115, 97, 102, 101, 95, 108,
        101, 110, 44, 32, 110, 97, 109, 101, 95, 112, 116, 114, 41, 32, 33, 61, 32, 48, 41, 0, 32,
        32, 32, 32, 98, 112, 102, 95, 112, 114, 105, 110, 116, 107, 40, 34, 83, 112, 101, 99, 105,
        101, 115, 32, 78, 97, 109, 101, 58, 32, 37, 115, 32, 40, 83, 112, 101, 99, 105, 101, 115,
        32, 108, 101, 110, 61, 37, 100, 41, 92, 110, 34, 44, 32, 115, 112, 101, 99, 105, 101, 115,
        95, 98, 117, 102, 44, 32, 115, 112, 101, 99, 105, 101, 115, 95, 115, 97, 102, 101, 95, 108,
        101, 110, 41, 59, 0, 32, 32, 32, 32, 98, 112, 102, 95, 112, 114, 105, 110, 116, 107, 40,
        34, 65, 103, 101, 58, 32, 37, 108, 100, 92, 110, 34, 44, 32, 97, 103, 101, 41, 59, 0, 32,
        32, 32, 32, 98, 112, 102, 95, 112, 114, 105, 110, 116, 107, 40, 34, 73, 115, 87, 105, 108,
        100, 58, 32, 37, 115, 92, 110, 34, 44, 32, 105, 115, 95, 119, 105, 108, 100, 32, 63, 32,
        34, 116, 114, 117, 101, 34, 32, 58, 32, 34, 102, 97, 108, 115, 101, 34, 41, 59, 0, 108,
        105, 99, 101, 110, 115, 101, 0, 46, 114, 111, 100, 97, 116, 97, 0, 117, 112, 114, 111, 98,
        101, 47, 109, 97, 105, 110, 46, 104, 101, 108, 108, 111, 95, 105, 110, 116, 0, 117, 112,
        114, 111, 98, 101, 47, 109, 97, 105, 110, 46, 104, 101, 108, 108, 111, 95, 105, 110, 116,
        95, 115, 116, 114, 105, 110, 103, 0, 117, 112, 114, 111, 98, 101, 47, 104, 97, 110, 100,
        108, 101, 95, 104, 101, 108, 108, 111, 95, 115, 116, 114, 117, 99, 116, 95, 112, 111, 105,
        110, 116, 101, 114, 0, 117, 112, 114, 111, 98, 101, 47, 104, 97, 110, 100, 108, 101, 95,
        104, 101, 108, 108, 111, 95, 115, 116, 114, 117, 99, 116, 95, 118, 97, 108, 117, 101, 0, 0,
        0, 0, 0, 0, 0, 159, 235, 1, 0, 32, 0, 0, 0, 0, 0, 0, 0, 68, 0, 0, 0, 68, 0, 0, 0, 116, 5,
        0, 0, 184, 5, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 7, 17, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 6, 0, 0,
        0, 29, 17, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 7, 0, 0, 0, 58, 17, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        8, 0, 0, 0, 93, 17, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 9, 0, 0, 0, 16, 0, 0, 0, 7, 17, 0, 0, 4,
        0, 0, 0, 0, 0, 0, 0, 38, 4, 0, 0, 64, 4, 0, 0, 23, 48, 0, 0, 8, 0, 0, 0, 38, 4, 0, 0, 90,
        4, 0, 0, 5, 52, 0, 0, 40, 0, 0, 0, 38, 4, 0, 0, 137, 4, 0, 0, 5, 56, 0, 0, 80, 0, 0, 0, 38,
        4, 0, 0, 178, 4, 0, 0, 5, 60, 0, 0, 29, 17, 0, 0, 15, 0, 0, 0, 0, 0, 0, 0, 38, 4, 0, 0,
        192, 4, 0, 0, 34, 92, 0, 0, 8, 0, 0, 0, 38, 4, 0, 0, 252, 4, 0, 0, 25, 128, 0, 0, 56, 0, 0,
        0, 38, 4, 0, 0, 40, 5, 0, 0, 14, 140, 0, 0, 136, 0, 0, 0, 38, 4, 0, 0, 88, 5, 0, 0, 29,
        152, 0, 0, 144, 0, 0, 0, 38, 4, 0, 0, 150, 5, 0, 0, 13, 160, 0, 0, 192, 0, 0, 0, 38, 4, 0,
        0, 219, 5, 0, 0, 9, 240, 0, 0, 216, 0, 0, 0, 38, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 224, 0,
        0, 0, 38, 4, 0, 0, 21, 6, 0, 0, 1, 0, 1, 0, 248, 0, 0, 0, 38, 4, 0, 0, 23, 6, 0, 0, 20,
        172, 0, 0, 16, 1, 0, 0, 38, 4, 0, 0, 94, 6, 0, 0, 13, 176, 0, 0, 24, 1, 0, 0, 38, 4, 0, 0,
        115, 6, 0, 0, 13, 184, 0, 0, 56, 1, 0, 0, 38, 4, 0, 0, 166, 6, 0, 0, 13, 200, 0, 0, 72, 1,
        0, 0, 38, 4, 0, 0, 209, 6, 0, 0, 13, 208, 0, 0, 96, 1, 0, 0, 38, 4, 0, 0, 209, 6, 0, 0, 34,
        208, 0, 0, 112, 1, 0, 0, 38, 4, 0, 0, 250, 6, 0, 0, 9, 220, 0, 0, 58, 17, 0, 0, 34, 0, 0,
        0, 0, 0, 0, 0, 38, 4, 0, 0, 56, 7, 0, 0, 33, 104, 1, 0, 8, 0, 0, 0, 38, 4, 0, 0, 121, 7, 0,
        0, 9, 112, 1, 0, 16, 0, 0, 0, 38, 4, 0, 0, 143, 7, 0, 0, 9, 120, 1, 0, 64, 0, 0, 0, 38, 4,
        0, 0, 190, 7, 0, 0, 9, 148, 1, 0, 88, 0, 0, 0, 38, 4, 0, 0, 190, 7, 0, 0, 9, 148, 1, 0, 96,
        0, 0, 0, 38, 4, 0, 0, 8, 8, 0, 0, 9, 156, 1, 0, 144, 0, 0, 0, 38, 4, 0, 0, 63, 8, 0, 0, 10,
        176, 1, 0, 208, 0, 0, 0, 38, 4, 0, 0, 92, 8, 0, 0, 32, 180, 1, 0, 224, 0, 0, 0, 38, 4, 0,
        0, 133, 8, 0, 0, 25, 184, 1, 0, 232, 0, 0, 0, 38, 4, 0, 0, 192, 8, 0, 0, 9, 192, 1, 0, 0,
        1, 0, 0, 38, 4, 0, 0, 1, 9, 0, 0, 30, 208, 1, 0, 24, 1, 0, 0, 38, 4, 0, 0, 70, 9, 0, 0, 64,
        216, 1, 0, 48, 1, 0, 0, 38, 4, 0, 0, 70, 9, 0, 0, 13, 216, 1, 0, 64, 1, 0, 0, 38, 4, 0, 0,
        70, 9, 0, 0, 13, 216, 1, 0, 80, 1, 0, 0, 38, 4, 0, 0, 149, 9, 0, 0, 13, 224, 1, 0, 112, 1,
        0, 0, 38, 4, 0, 0, 149, 9, 0, 0, 35, 224, 1, 0, 120, 1, 0, 0, 38, 4, 0, 0, 191, 9, 0, 0,
        13, 228, 1, 0, 168, 1, 0, 0, 38, 4, 0, 0, 11, 10, 0, 0, 10, 244, 1, 0, 232, 1, 0, 0, 38, 4,
        0, 0, 43, 10, 0, 0, 40, 248, 1, 0, 248, 1, 0, 0, 38, 4, 0, 0, 95, 10, 0, 0, 33, 252, 1, 0,
        0, 2, 0, 0, 38, 4, 0, 0, 170, 10, 0, 0, 9, 4, 2, 0, 16, 2, 0, 0, 38, 4, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 40, 2, 0, 0, 38, 4, 0, 0, 243, 10, 0, 0, 33, 16, 2, 0, 64, 2, 0, 0, 38, 4, 0,
        0, 65, 11, 0, 0, 75, 24, 2, 0, 88, 2, 0, 0, 38, 4, 0, 0, 65, 11, 0, 0, 13, 24, 2, 0, 104,
        2, 0, 0, 38, 4, 0, 0, 65, 11, 0, 0, 13, 24, 2, 0, 120, 2, 0, 0, 38, 4, 0, 0, 158, 11, 0, 0,
        13, 32, 2, 0, 152, 2, 0, 0, 38, 4, 0, 0, 158, 11, 0, 0, 46, 32, 2, 0, 160, 2, 0, 0, 38, 4,
        0, 0, 211, 11, 0, 0, 13, 36, 2, 0, 200, 2, 0, 0, 38, 4, 0, 0, 40, 12, 0, 0, 5, 56, 2, 0,
        240, 2, 0, 0, 38, 4, 0, 0, 83, 12, 0, 0, 5, 60, 2, 0, 24, 3, 0, 0, 38, 4, 0, 0, 132, 12, 0,
        0, 5, 64, 2, 0, 96, 3, 0, 0, 38, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 104, 3, 0, 0, 38, 4, 0,
        0, 21, 6, 0, 0, 1, 76, 2, 0, 93, 17, 0, 0, 32, 0, 0, 0, 0, 0, 0, 0, 38, 4, 0, 0, 200, 12,
        0, 0, 31, 124, 2, 0, 8, 0, 0, 0, 38, 4, 0, 0, 240, 12, 0, 0, 27, 120, 2, 0, 16, 0, 0, 0,
        38, 4, 0, 0, 25, 13, 0, 0, 35, 108, 2, 0, 24, 0, 0, 0, 38, 4, 0, 0, 78, 13, 0, 0, 30, 96,
        2, 0, 32, 0, 0, 0, 38, 4, 0, 0, 131, 13, 0, 0, 32, 100, 2, 0, 48, 0, 0, 0, 38, 4, 0, 0, 63,
        8, 0, 0, 10, 132, 2, 0, 112, 0, 0, 0, 38, 4, 0, 0, 184, 13, 0, 0, 23, 136, 2, 0, 136, 0, 0,
        0, 38, 4, 0, 0, 216, 13, 0, 0, 25, 144, 2, 0, 152, 0, 0, 0, 38, 4, 0, 0, 216, 13, 0, 0, 9,
        144, 2, 0, 160, 0, 0, 0, 38, 4, 0, 0, 192, 8, 0, 0, 9, 152, 2, 0, 192, 0, 0, 0, 38, 4, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 216, 0, 0, 0, 38, 4, 0, 0, 20, 14, 0, 0, 14, 176, 2, 0, 232, 0,
        0, 0, 38, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 240, 0, 0, 0, 38, 4, 0, 0, 83, 14, 0, 0, 9, 204,
        2, 0, 8, 1, 0, 0, 38, 4, 0, 0, 83, 14, 0, 0, 9, 204, 2, 0, 16, 1, 0, 0, 38, 4, 0, 0, 147,
        14, 0, 0, 9, 212, 2, 0, 32, 1, 0, 0, 38, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 48, 1, 0, 0, 38,
        4, 0, 0, 21, 6, 0, 0, 1, 92, 3, 0, 72, 1, 0, 0, 38, 4, 0, 0, 194, 14, 0, 0, 5, 228, 2, 0,
        128, 1, 0, 0, 38, 4, 0, 0, 11, 10, 0, 0, 10, 236, 2, 0, 192, 1, 0, 0, 38, 4, 0, 0, 253, 14,
        0, 0, 27, 240, 2, 0, 216, 1, 0, 0, 38, 4, 0, 0, 36, 15, 0, 0, 29, 248, 2, 0, 232, 1, 0, 0,
        38, 4, 0, 0, 36, 15, 0, 0, 9, 248, 2, 0, 240, 1, 0, 0, 38, 4, 0, 0, 107, 15, 0, 0, 9, 0, 3,
        0, 24, 2, 0, 0, 38, 4, 0, 0, 176, 15, 0, 0, 22, 24, 3, 0, 40, 2, 0, 0, 38, 4, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 48, 2, 0, 0, 38, 4, 0, 0, 247, 15, 0, 0, 9, 52, 3, 0, 72, 2, 0, 0, 38, 4,
        0, 0, 247, 15, 0, 0, 9, 52, 3, 0, 80, 2, 0, 0, 38, 4, 0, 0, 147, 14, 0, 0, 9, 60, 3, 0,
        112, 2, 0, 0, 38, 4, 0, 0, 66, 16, 0, 0, 5, 72, 3, 0, 160, 2, 0, 0, 38, 4, 0, 0, 152, 16,
        0, 0, 5, 76, 3, 0, 200, 2, 0, 0, 38, 4, 0, 0, 187, 16, 0, 0, 5, 80, 3, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
        0, 0, 3, 0, 0, 0, 32, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 64, 0, 0, 0, 0, 0, 0, 0,
        181, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 9, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 248, 5, 0, 0,
        0, 0, 0, 0, 232, 5, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 24,
        0, 0, 0, 0, 0, 0, 0, 17, 0, 0, 0, 1, 0, 0, 0, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 224, 11, 0, 0, 0, 0, 0, 0, 96, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 39, 0, 0, 0, 1, 0, 0, 0, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 64, 12, 0, 0, 0, 0, 0, 0, 168, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 68, 0, 0, 0, 1, 0, 0, 0, 6, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 232, 13, 0, 0, 0, 0, 0, 0, 120, 3, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 103, 0, 0, 0, 1, 0, 0, 0,
        6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 96, 17, 0, 0, 0, 0, 0, 0, 24, 3, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 136, 0, 0,
        0, 1, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 120, 20, 0, 0, 0, 0, 0, 0,
        13, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 144, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 133, 20, 0,
        0, 0, 0, 0, 0, 10, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 152, 0, 0, 0, 1, 0, 0, 0, 50, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 143, 22, 0, 0, 0, 0, 0, 0, 11, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
        0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 32, 5, 0, 0, 9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 160, 22, 0, 0, 0, 0, 0, 0, 32, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 3, 0,
        0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 16, 0, 0, 0, 0, 0, 0, 0, 58, 5, 0, 0, 9, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 192, 22, 0, 0, 0, 0, 0, 0, 64, 0, 0, 0, 0, 0, 0, 0, 2,
        0, 0, 0, 4, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 16, 0, 0, 0, 0, 0, 0, 0, 91, 5, 0, 0, 9, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 23, 0, 0, 0, 0, 0, 0, 176, 0, 0, 0,
        0, 0, 0, 0, 2, 0, 0, 0, 5, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 16, 0, 0, 0, 0, 0, 0, 0, 130,
        5, 0, 0, 9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 176, 23, 0, 0, 0, 0,
        0, 0, 160, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 6, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 16, 0, 0,
        0, 0, 0, 0, 0, 167, 5, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        80, 24, 0, 0, 0, 0, 0, 0, 66, 23, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 172, 5, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 152, 47, 0, 0, 0, 0, 0, 0, 216, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    ];
}
